//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kioskplus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class kioskplustr_TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal kioskplustr_TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kioskplus.kioskplustr-TR", typeof(kioskplustr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( * ) bulunan bütün alanlar doldurulmak zorunda..
        /// </summary>
        internal static string allgEingabeError {
            get {
                return ResourceManager.GetString("allgEingabeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet bağlantınızı kontrol ediniz..
        /// </summary>
        internal static string allgInternetError {
            get {
                return ResourceManager.GetString("allgInternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler kontrol ediliyor.....
        /// </summary>
        internal static string aufladenMsg {
            get {
                return ResourceManager.GetString("aufladenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz bulunamadı. Lütfen ayarlarınızı kontrol ediniz..
        /// </summary>
        internal static string billErrorFound {
            get {
                return ResourceManager.GetString("billErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir Cihaz bulundu.Lütfen ayarlarını yapınız..
        /// </summary>
        internal static string billSuccessFound {
            get {
                return ResourceManager.GetString("billSuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bekleyin. . ..
        /// </summary>
        internal static string bittewarten {
            get {
                return ResourceManager.GetString("bittewarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS`iniz gönderiliyor.Lütfen bekleyiniz....
        /// </summary>
        internal static string bittewartenSMS {
            get {
                return ResourceManager.GetString("bittewartenSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İki katı.
        /// </summary>
        internal static string blackDoppeln {
            get {
                return ResourceManager.GetString("blackDoppeln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maalesef  Bahsi ikiye katlayamazsınız ,çünkü Kontörünüz yeterli değil ! Lütfen Para atınız..
        /// </summary>
        internal static string blackDoppelnError {
            get {
                return ResourceManager.GetString("blackDoppelnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin Bahsiniz: {0}.
        /// </summary>
        internal static string blackEinsatz {
            get {
                return ResourceManager.GetString("blackEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahisi sil.
        /// </summary>
        internal static string blackEinsatzDelete {
            get {
                return ResourceManager.GetString("blackEinsatzDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bahsinizi giriniz.
        /// </summary>
        internal static string blackErrorEinsatz {
            get {
                return ResourceManager.GetString("blackErrorEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazandınız.
        /// </summary>
        internal static string blackGewonnen {
            get {
                return ResourceManager.GetString("blackGewonnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaybettiniz.
        /// </summary>
        internal static string blackKVerloren {
            get {
                return ResourceManager.GetString("blackKVerloren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. dakika: {0}.
        /// </summary>
        internal static string blackMaxEinsatz {
            get {
                return ResourceManager.GetString("blackMaxEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Bahisi aşıyor.
        /// </summary>
        internal static string blackMaxEinsatzUeber {
            get {
                return ResourceManager.GetString("blackMaxEinsatzUeber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kabul et.
        /// </summary>
        internal static string blackNehmen {
            get {
                return ResourceManager.GetString("blackNehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böl.
        /// </summary>
        internal static string blackSplitten {
            get {
                return ResourceManager.GetString("blackSplitten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maalesef  BÖL seçeneğini kullanamazsınız , çünkü ilave bahis için Kontörünüz yeterli değil ! Lütfen para atınız..
        /// </summary>
        internal static string blackSplittenError {
            get {
                return ResourceManager.GetString("blackSplittenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dur.
        /// </summary>
        internal static string blackStehen {
            get {
                return ResourceManager.GetString("blackStehen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berabere.
        /// </summary>
        internal static string blackUnentschieden {
            get {
                return ResourceManager.GetString("blackUnentschieden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaybettiniz.
        /// </summary>
        internal static string blackVerloren {
            get {
                return ResourceManager.GetString("blackVerloren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigortalamak istiyormusunuz?.
        /// </summary>
        internal static string blackVersichern {
            get {
                return ResourceManager.GetString("blackVersichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam.
        /// </summary>
        internal static string blackWeiter {
            get {
                return ResourceManager.GetString("blackWeiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu KIOSK-ID kilitli!.
        /// </summary>
        internal static string blockedID {
            get {
                return ResourceManager.GetString("blockedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitir.
        /// </summary>
        internal static string btnBeenden {
            get {
                return ResourceManager.GetString("btnBeenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Işleme son verildi..
        /// </summary>
        internal static string cancelLicenceAction {
            get {
                return ResourceManager.GetString("cancelLicenceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler kontrol ediliyor.....
        /// </summary>
        internal static string checkData {
            get {
                return ResourceManager.GetString("checkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbest bırakılıyor....
        /// </summary>
        internal static string checkFreigabe {
            get {
                return ResourceManager.GetString("checkFreigabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk-ID Kontrol ediliyor....
        /// </summary>
        internal static string checkID {
            get {
                return ResourceManager.GetString("checkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana sayfa kontrol ediliyor.
        /// </summary>
        internal static string checkSperrSeite {
            get {
                return ResourceManager.GetString("checkSperrSeite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kioskplus`u bitir.
        /// </summary>
        internal static string closeApp {
            get {
                return ResourceManager.GetString("closeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni hesap oluşturma aktif değil..
        /// </summary>
        internal static string deaktivKontoAnlegen {
            get {
                return ResourceManager.GetString("deaktivKontoAnlegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontör yükleme aktif değil..
        /// </summary>
        internal static string deaktivKontoAufladen {
            get {
                return ResourceManager.GetString("deaktivKontoAufladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün Dosyalar|*.*.
        /// </summary>
        internal static string dlgFileExtension {
            get {
                return ResourceManager.GetString("dlgFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir dosya seçiniz.
        /// </summary>
        internal static string dlgFileTitle {
            get {
                return ResourceManager.GetString("dlgFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış giriş.
        /// </summary>
        internal static string errorAufladenEingabe {
            get {
                return ResourceManager.GetString("errorAufladenEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz karakter.
        /// </summary>
        internal static string errorAufladenInvalidCharachter {
            get {
                return ResourceManager.GetString("errorAufladenInvalidCharachter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan zamanınız en az {0} dakika olmak zorunda.....
        /// </summary>
        internal static string errorAufladenNoMinute {
            get {
                return ResourceManager.GetString("errorAufladenNoMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Telefon numarasını düzeltiniz!.
        /// </summary>
        internal static string errorCheckTelNr {
            get {
                return ResourceManager.GetString("errorCheckTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir Ülke seçiniz!.
        /// </summary>
        internal static string errorChooseLand {
            get {
                return ResourceManager.GetString("errorChooseLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir telefon numarasi girin!.
        /// </summary>
        internal static string errorChooseTelNr {
            get {
                return ResourceManager.GetString("errorChooseTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontörünüz yeterli değil. Lütfen Kontör yükleyiniz!.
        /// </summary>
        internal static string errorDruckenGuthaben {
            get {
                return ResourceManager.GetString("errorDruckenGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail gönderilirken hata oluştu..
        /// </summary>
        internal static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir E-mail adresi girin!.
        /// </summary>
        internal static string errorEmailAdress {
            get {
                return ResourceManager.GetString("errorEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-Servisi aktif değil.
        /// </summary>
        internal static string errorEmailService {
            get {
                return ResourceManager.GetString("errorEmailService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen doğru Şifrinizi girin!.
        /// </summary>
        internal static string errorFalschPwd {
            get {
                return ResourceManager.GetString("errorFalschPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgi alanınızı seçiniz.
        /// </summary>
        internal static string errorhobby {
            get {
                return ResourceManager.GetString("errorhobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz karakter girildi ( {0} ).
        /// </summary>
        internal static string errorInValid {
            get {
                return ResourceManager.GetString("errorInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz KIOSK-ID .
        /// </summary>
        internal static string errorInvalidID {
            get {
                return ResourceManager.GetString("errorInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız geçersiz bir karakter içeriyor (&amp;=&apos;).
        /// </summary>
        internal static string errorInvalidNachricht {
            get {
                return ResourceManager.GetString("errorInvalidNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri numaranız yanlış. Lütfen geçerli bir müşteri numarası yazınız..
        /// </summary>
        internal static string errorKdNr {
            get {
                return ResourceManager.GetString("errorKdNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz KIOSK-ID yada geçersiz Şifre !.
        /// </summary>
        internal static string errorKioskIDorPwd {
            get {
                return ResourceManager.GetString("errorKioskIDorPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir Bozuk Para Aleti seçiniz yada &apos;Com-Port&apos;u  &apos;KAPALI &apos; duruma getiriniz..
        /// </summary>
        internal static string errorMP {
            get {
                return ResourceManager.GetString("errorMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bozuk Para Aletinin bağlı olduğu bir Com-port seçiniz yada &apos;Com-Port&apos;u  &apos;KAPALI &apos; duruma getiriniz..
        /// </summary>
        internal static string errorMPComPort {
            get {
                return ResourceManager.GetString("errorMPComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen İsminizi girin!.
        /// </summary>
        internal static string errorName {
            get {
                return ResourceManager.GetString("errorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen yeni bir Şifre girin!.
        /// </summary>
        internal static string errorNewPwdEingabe {
            get {
                return ResourceManager.GetString("errorNewPwdEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir Kullanıcı Adı ( Nick ) girin!.
        /// </summary>
        internal static string errorNickname {
            get {
                return ResourceManager.GetString("errorNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Mesajınızı yazınız!.
        /// </summary>
        internal static string errorNoNachricht {
            get {
                return ResourceManager.GetString("errorNoNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Fiyatı girin!.
        /// </summary>
        internal static string errorPreis {
            get {
                return ResourceManager.GetString("errorPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Şifre-Tekrar` ını  düzeltiniz!.
        /// </summary>
        internal static string errorPwdAgain {
            get {
                return ResourceManager.GetString("errorPwdAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Şifrenizi giriniz!.
        /// </summary>
        internal static string errorPwdEingabe {
            get {
                return ResourceManager.GetString("errorPwdEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS-Gönderme aktif değil.
        /// </summary>
        internal static string errorSmsDeaktiv {
            get {
                return ResourceManager.GetString("errorSmsDeaktiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamanınız (Kontörünz) yeterli değil !.
        /// </summary>
        internal static string errorSMSZeitGuthaben {
            get {
                return ResourceManager.GetString("errorSMSZeitGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Adınızı girin !.
        /// </summary>
        internal static string errorVorname {
            get {
                return ResourceManager.GetString("errorVorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kod Numarasını kontrol ediniz !.
        /// </summary>
        internal static string errorVorwahl {
            get {
                return ResourceManager.GetString("errorVorwahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kod Numarasını giriniz!.
        /// </summary>
        internal static string errorVorwahlEingabe {
            get {
                return ResourceManager.GetString("errorVorwahlEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam bulunamadı.
        /// </summary>
        internal static string errorWebCam {
            get {
                return ResourceManager.GetString("errorWebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bileşenleri doldurunuz.
        /// </summary>
        internal static string fillinstance {
            get {
                return ResourceManager.GetString("fillinstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açılıyor.....
        /// </summary>
        internal static string freigabeDurch {
            get {
                return ResourceManager.GetString("freigabeDurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol ediliyor ....
        /// </summary>
        internal static string freigabePruef {
            get {
                return ResourceManager.GetString("freigabePruef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgisayar açılıyor....
        /// </summary>
        internal static string freigabeTerminal {
            get {
                return ResourceManager.GetString("freigabeTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin için aşağıdaki Kiosk-ID yi oluşturduk. {0} Bu Kiosk-ID için geçerli şifreniz &quot;inetplus&quot;. {1} Kiosk-ID niz: {2}.
        /// </summary>
        internal static string getfreelicence {
            get {
                return ResourceManager.GetString("getfreelicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükleme de hata oluştu. Lütfen yüklemeyi tekrarlayınız..
        /// </summary>
        internal static string incompleteInstall {
            get {
                return ResourceManager.GetString("incompleteInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | aktif.
        /// </summary>
        internal static string infoActive {
            get {
                return ResourceManager.GetString("infoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kağıt para aleti.
        /// </summary>
        internal static string infoBill {
            get {
                return ResourceManager.GetString("infoBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | aktif değil.
        /// </summary>
        internal static string infoDeactive {
            get {
                return ResourceManager.GetString("infoDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata {0}.
        /// </summary>
        internal static string infoErrorEnde {
            get {
                return ResourceManager.GetString("infoErrorEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sohbet.
        /// </summary>
        internal static string infoGames {
            get {
                return ResourceManager.GetString("infoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı hesapları.
        /// </summary>
        internal static string infoIkunden {
            get {
                return ResourceManager.GetString("infoIkunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bozuk para aleti.
        /// </summary>
        internal static string infoMP {
            get {
                return ResourceManager.GetString("infoMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bozuk Para Aleti ve Kağıt para okuyucu.
        /// </summary>
        internal static string infoMPBill {
            get {
                return ResourceManager.GetString("infoMPBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS-Gönder.
        /// </summary>
        internal static string infoSMS {
            get {
                return ResourceManager.GetString("infoSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla bitirildi.
        /// </summary>
        internal static string infoSuccessEnde {
            get {
                return ResourceManager.GetString("infoSuccessEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string infoVoip {
            get {
                return ResourceManager.GetString("infoVoip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullancı adı yada Şifre yanlış.
        /// </summary>
        internal static string kpc1 {
            get {
                return ResourceManager.GetString("kpc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupon kilitlenmiş !.
        /// </summary>
        internal static string kpc10 {
            get {
                return ResourceManager.GetString("kpc10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupon kullanılmış !.
        /// </summary>
        internal static string kpc11 {
            get {
                return ResourceManager.GetString("kpc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğunuz ülkede şu an icin ücretsiz lisans desteği bulunmamaktadır. Ücretli lisans kullanmak ister misiniz?.
        /// </summary>
        internal static string kpc112 {
            get {
                return ResourceManager.GetString("kpc112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel bir hata oluştu. Lütfen daha sonra tekrar deneyiniz..
        /// </summary>
        internal static string kpc113 {
            get {
                return ResourceManager.GetString("kpc113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri numaranız yada şifreniz yanlış. Lütfen bilgilerinizi tekrar giriniz..
        /// </summary>
        internal static string kpc114 {
            get {
                return ResourceManager.GetString("kpc114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geçersiz.
        /// </summary>
        internal static string kpc12 {
            get {
                return ResourceManager.GetString("kpc12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi &apos;yüklenebilir Kupon&apos; değil. Sadece bir defalık kullanım mümkün!.
        /// </summary>
        internal static string kpc13 {
            get {
                return ResourceManager.GetString("kpc13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Versiyon sadece Register dan sonra kullanılabilir. Lütfen sorularınızı bu adrese yollayınız support@inetplus.de.
        /// </summary>
        internal static string kpc14 {
            get {
                return ResourceManager.GetString("kpc14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz KIOSK-ID yada geçersiz Şifre !.
        /// </summary>
        internal static string kpc15 {
            get {
                return ResourceManager.GetString("kpc15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu KIOSK-ID geçersiz !.
        /// </summary>
        internal static string kpc16 {
            get {
                return ResourceManager.GetString("kpc16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS krediniz yetersiz ..
        /// </summary>
        internal static string kpc17 {
            get {
                return ResourceManager.GetString("kpc17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediniz yetersiz..
        /// </summary>
        internal static string kpc18 {
            get {
                return ResourceManager.GetString("kpc18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı kullanımda. Lütfen başkasını seçin!.
        /// </summary>
        internal static string kpc19 {
            get {
                return ResourceManager.GetString("kpc19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı oturum açmış durumda .
        /// </summary>
        internal static string kpc2 {
            get {
                return ResourceManager.GetString("kpc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bir daha ki girilecek yanlış bilgi ile KIOSK-ID kilitlenecektir..
        /// </summary>
        internal static string kpc20 {
            get {
                return ResourceManager.GetString("kpc20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış şifre.
        /// </summary>
        internal static string kpc3 {
            get {
                return ResourceManager.GetString("kpc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto buraya ait değil.
        /// </summary>
        internal static string kpc4 {
            get {
                return ResourceManager.GetString("kpc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto kapatılmış.
        /// </summary>
        internal static string kpc5 {
            get {
                return ResourceManager.GetString("kpc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto silinmiş.
        /// </summary>
        internal static string kpc6 {
            get {
                return ResourceManager.GetString("kpc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontonuz boş. Lütfen doldurun!.
        /// </summary>
        internal static string kpc7 {
            get {
                return ResourceManager.GetString("kpc7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz yer (Share)!.
        /// </summary>
        internal static string kpc8 {
            get {
                return ResourceManager.GetString("kpc8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontonuz başka yerde açılı !.
        /// </summary>
        internal static string kpc9 {
            get {
                return ResourceManager.GetString("kpc9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birkaç saniye içinde kullanmakta olduğun Bilgisayarın  .
        /// </summary>
        internal static string last1Minuten {
            get {
                return ResourceManager.GetString("last1Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanmakta olduğun Bilgisayar kapatılacaktır.Lütfen kendini hazırla  119 . . . . 117 . . . . 115.
        /// </summary>
        internal static string last2Minuten {
            get {
                return ResourceManager.GetString("last2Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zamanın daralıyor..
        /// </summary>
        internal static string last3Minuten {
            get {
                return ResourceManager.GetString("last3Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daha sonra Bilgisayarın kapatılacaktır..
        /// </summary>
        internal static string last4Minuten {
            get {
                return ResourceManager.GetString("last4Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daha sonra Bilgisayarın kapatılacaktır.Lütfen vaktinde zamanını uzatmayı unutma..
        /// </summary>
        internal static string last5Minuten {
            get {
                return ResourceManager.GetString("last5Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece  {0} dakikan kaldı. . ..
        /// </summary>
        internal static string lastMinutenNoch {
            get {
                return ResourceManager.GetString("lastMinutenNoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support-Bağlantı.
        /// </summary>
        internal static string menu01 {
            get {
                return ResourceManager.GetString("menu01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        internal static string menu02 {
            get {
                return ResourceManager.GetString("menu02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu kapat.
        /// </summary>
        internal static string menu03 {
            get {
                return ResourceManager.GetString("menu03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Inetplus`u değiştir.
        /// </summary>
        internal static string menu04 {
            get {
                return ResourceManager.GetString("menu04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Inetplus aktif değil.
        /// </summary>
        internal static string menu05 {
            get {
                return ResourceManager.GetString("menu05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Inetplus aktif.
        /// </summary>
        internal static string menu052 {
            get {
                return ResourceManager.GetString("menu052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack.
        /// </summary>
        internal static string menu06 {
            get {
                return ResourceManager.GetString("menu06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf yolla.
        /// </summary>
        internal static string menu07 {
            get {
                return ResourceManager.GetString("menu07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyunlar.
        /// </summary>
        internal static string menu08 {
            get {
                return ResourceManager.GetString("menu08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bozuk para aleti bulanamadı.Lütfen Ayarlarınızı kontrol ediniz..
        /// </summary>
        internal static string mpErrorFound {
            get {
                return ResourceManager.GetString("mpErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğru olan Bozuk para aleti bulunamadı.Lütfen kontrol ediniz ..
        /// </summary>
        internal static string mpErrorFoundII {
            get {
                return ResourceManager.GetString("mpErrorFoundII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Bozuk para aleti desteklenmiyor. Hata Kodu: 00H3F47.
        /// </summary>
        internal static string mpFoundFalse {
            get {
                return ResourceManager.GetString("mpFoundFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bozuk para aleti bulunamıyor. Lütfen ayarlayınız..
        /// </summary>
        internal static string mpSuccessFound {
            get {
                return ResourceManager.GetString("mpSuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kioskplus yeniden başlatılmak zorunda! Devam etmek için lütfen &apos;Tamam&apos; a basın..
        /// </summary>
        internal static string msgAppNeuStart {
            get {
                return ResourceManager.GetString("msgAppNeuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün bilgilerin güncellenebilmesi için bilgisayar yeniden başlatılıyor! {0}Devam etmek için lütfen &apos;Tamam&apos; a basın..
        /// </summary>
        internal static string msgPCNeuStart {
            get {
                return ResourceManager.GetString("msgPCNeuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba {0} . . .Ben Ajan {1}.
        /// </summary>
        internal static string newAgent {
            get {
                return ResourceManager.GetString("newAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen para atmayınız! Bilgisayar 5 saniye içerisinde yeniden başlatılıyor!.
        /// </summary>
        internal static string noMoneyInsert {
            get {
                return ResourceManager.GetString("noMoneyInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bileşenler yükleniyor....
        /// </summary>
        internal static string objLaden {
            get {
                return ResourceManager.GetString("objLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online-Update (Adım &gt;&gt; {0} &lt;&lt; ).
        /// </summary>
        internal static string onlineUpd {
            get {
                return ResourceManager.GetString("onlineUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapalı.
        /// </summary>
        internal static string portAus {
            get {
                return ResourceManager.GetString("portAus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat-Fiyatı:.
        /// </summary>
        internal static string preisTitle {
            get {
                return ResourceManager.GetString("preisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir SMS`in fiyatı {0} dakika (={1}  {2}).
        /// </summary>
        internal static string proSMSKostet {
            get {
                return ResourceManager.GetString("proSMSKostet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot ayarları okunuyor....
        /// </summary>
        internal static string readBootProperty {
            get {
                return ResourceManager.GetString("readBootProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID-Bilgileri okunuyor....
        /// </summary>
        internal static string readGUID {
            get {
                return ResourceManager.GetString("readGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Merkezi bilgileri okunuyor...
        /// </summary>
        internal static string readKC {
            get {
                return ResourceManager.GetString("readKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Merkezi fiyatları okunuyor....
        /// </summary>
        internal static string readKCPreis {
            get {
                return ResourceManager.GetString("readKCPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazıcı fiyatı okunuyor....
        /// </summary>
        internal static string readKCPrint {
            get {
                return ResourceManager.GetString("readKCPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuşları ve fiyatları oku....
        /// </summary>
        internal static string readKeyAndPrise {
            get {
                return ResourceManager.GetString("readKeyAndPrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gençleri koruma programı ayarları ....
        /// </summary>
        internal static string readProtectOfMinor {
            get {
                return ResourceManager.GetString("readProtectOfMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bekleyiniz! Bağlantı kuruluyor . . ..
        /// </summary>
        internal static string sipBitteWarten {
            get {
                return ResourceManager.GetString("sipBitteWarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüşme bitti. . ..
        /// </summary>
        internal static string sipCallingEnde {
            get {
                return ResourceManager.GetString("sipCallingEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numara aranıyor. . ..
        /// </summary>
        internal static string sipCallingNumber {
            get {
                return ResourceManager.GetString("sipCallingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP bağlantı portu açılamıyor..
        /// </summary>
        internal static string sipCommError {
            get {
                return ResourceManager.GetString("sipCommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı değilsiniz.Lütfen tercih tuşunu harekete geçirin.
        /// </summary>
        internal static string sipError10 {
            get {
                return ResourceManager.GetString("sipError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı meşgul.
        /// </summary>
        internal static string sipError11 {
            get {
                return ResourceManager.GetString("sipError11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans`da hata var.
        /// </summary>
        internal static string sipError12 {
            get {
                return ResourceManager.GetString("sipError12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bileşenlerinde hata .
        /// </summary>
        internal static string sipError13 {
            get {
                return ResourceManager.GetString("sipError13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrofon mevcut değil yada başka uygulamada kullanılıyor.
        /// </summary>
        internal static string sipError14 {
            get {
                return ResourceManager.GetString("sipError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopörlör mevcut değil yada başka uygulamada kullanılıyor..
        /// </summary>
        internal static string sipError15 {
            get {
                return ResourceManager.GetString("sipError15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrofon mevcut değil.
        /// </summary>
        internal static string sipError16 {
            get {
                return ResourceManager.GetString("sipError16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopörlör  mevcut değil.
        /// </summary>
        internal static string sipError17 {
            get {
                return ResourceManager.GetString("sipError17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopörlör ses ayarlarını desteklemiyor.
        /// </summary>
        internal static string sipError18 {
            get {
                return ResourceManager.GetString("sipError18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopörlör ses ayarlarını desteklemiyor.
        /// </summary>
        internal static string sipError19 {
            get {
                return ResourceManager.GetString("sipError19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt yapılamadı.
        /// </summary>
        internal static string sipError20 {
            get {
                return ResourceManager.GetString("sipError20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.wav uzantılı dosya açılamadı.
        /// </summary>
        internal static string sipError21 {
            get {
                return ResourceManager.GetString("sipError21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bileşenlerde hata.
        /// </summary>
        internal static string sipError22 {
            get {
                return ResourceManager.GetString("sipError22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec desteklenmiyor.
        /// </summary>
        internal static string sipError23 {
            get {
                return ResourceManager.GetString("sipError23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDP-sorgusu yapılamadı..
        /// </summary>
        internal static string sipError24 {
            get {
                return ResourceManager.GetString("sipError24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError25 {
            get {
                return ResourceManager.GetString("sipError25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError26 {
            get {
                return ResourceManager.GetString("sipError26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError27 {
            get {
                return ResourceManager.GetString("sipError27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError28 {
            get {
                return ResourceManager.GetString("sipError28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError29 {
            get {
                return ResourceManager.GetString("sipError29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata (meşgul).
        /// </summary>
        internal static string sipError30 {
            get {
                return ResourceManager.GetString("sipError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError31 {
            get {
                return ResourceManager.GetString("sipError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError32 {
            get {
                return ResourceManager.GetString("sipError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError33 {
            get {
                return ResourceManager.GetString("sipError33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon bağlantısında hata.
        /// </summary>
        internal static string sipError34 {
            get {
                return ResourceManager.GetString("sipError34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wav uzantılı dosyanın okunmasında hata oluştu.
        /// </summary>
        internal static string sipError35 {
            get {
                return ResourceManager.GetString("sipError35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wav uzantılı dosyanın yazımında hata oluştu.
        /// </summary>
        internal static string sipError36 {
            get {
                return ResourceManager.GetString("sipError36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya türü desteklenmiyor.
        /// </summary>
        internal static string sipError37 {
            get {
                return ResourceManager.GetString("sipError37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz bağlantı bilgileri.
        /// </summary>
        internal static string sipErrorDaten {
            get {
                return ResourceManager.GetString("sipErrorDaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontörünüz bitmek üzere!.
        /// </summary>
        internal static string sipErrorGuthaben {
            get {
                return ResourceManager.GetString("sipErrorGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz numara.
        /// </summary>
        internal static string sipErrorInvalidNr {
            get {
                return ResourceManager.GetString("sipErrorInvalidNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat tanımlanmamış (YTL).
        /// </summary>
        internal static string sipErrorNoDefinePreis {
            get {
                return ResourceManager.GetString("sipErrorNoDefinePreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat tanımlanmamış (Birim).
        /// </summary>
        internal static string sipErrorNoDefineWaehrung {
            get {
                return ResourceManager.GetString("sipErrorNoDefineWaehrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontör tükendi !.
        /// </summary>
        internal static string sipErrorNoGuthaben {
            get {
                return ResourceManager.GetString("sipErrorNoGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı için boş bir Port mevcut değil..
        /// </summary>
        internal static string sipErrorPort {
            get {
                return ResourceManager.GetString("sipErrorPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir Telefonnumarası girin!.
        /// </summary>
        internal static string sipErrorTelNr {
            get {
                return ResourceManager.GetString("sipErrorTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediniz bitmiştir.Lütfen doldurun.
        /// </summary>
        internal static string sipKontoGuthaben {
            get {
                return ResourceManager.GetString("sipKontoGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon aktif değil.
        /// </summary>
        internal static string sipNoAllow {
            get {
                return ResourceManager.GetString("sipNoAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüşme başladı !.
        /// </summary>
        internal static string sipStartCalling {
            get {
                return ResourceManager.GetString("sipStartCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla bitirildi.
        /// </summary>
        internal static string sipSuccessEnde {
            get {
                return ResourceManager.GetString("sipSuccessEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontörünüz çok az.Lütfen para atın..
        /// </summary>
        internal static string sipZeitGuthaben {
            get {
                return ResourceManager.GetString("sipZeitGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt olmadan bedava arkadaşlarına Email yolla..
        /// </summary>
        internal static string skin1 {
            get {
                return ResourceManager.GetString("skin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok basit. Üç adımda ücretsiz bir konto aç ve geri kalan zamanını istediğin zaman kullan.
        /// </summary>
        internal static string skin2 {
            get {
                return ResourceManager.GetString("skin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahip oldugun kontona kredi yüklemek istemez misin? Alacağın kupon bilgilerini burada girmen yeterli!.
        /// </summary>
        internal static string skin3 {
            get {
                return ResourceManager.GetString("skin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldukça rahat, hızlı ve uygun fiyatlara SMS bu terminal den yollayabilirsin.
        /// </summary>
        internal static string skin4 {
            get {
                return ResourceManager.GetString("skin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşcakal {0}, sana iyi günler dilerim. Umarım tekrar gelirsin.
        /// </summary>
        internal static string skin5 {
            get {
                return ResourceManager.GetString("skin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu terminal den istediğin her yere oldukça uygun fiyatlara telefon edebilirsin.
        /// </summary>
        internal static string skin6 {
            get {
                return ResourceManager.GetString("skin6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha  {0} adet SMS  gönderilebilir..
        /// </summary>
        internal static string smsKonto {
            get {
                return ResourceManager.GetString("smsKonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazır değil!!.
        /// </summary>
        internal static string smsLandListe {
            get {
                return ResourceManager.GetString("smsLandListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol başarılı.
        /// </summary>
        internal static string successCheck {
            get {
                return ResourceManager.GetString("successCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı başarılı.
        /// </summary>
        internal static string successConnect {
            get {
                return ResourceManager.GetString("successConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email başarıyla yollandı !.
        /// </summary>
        internal static string successEmail {
            get {
                return ResourceManager.GetString("successEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazır !.
        /// </summary>
        internal static string successEnde {
            get {
                return ResourceManager.GetString("successEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri bilgileri başarıyla kaydedildi.
        /// </summary>
        internal static string successSaveKD {
            get {
                return ResourceManager.GetString("successSaveKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS başarıyla yollandı..
        /// </summary>
        internal static string successSMS {
            get {
                return ResourceManager.GetString("successSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet bağlantısı aranıyor....
        /// </summary>
        internal static string sucheInternet {
            get {
                return ResourceManager.GetString("sucheInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote bağlantı numarası bulunamadı!.
        /// </summary>
        internal static string supportText {
            get {
                return ResourceManager.GetString("supportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . . ..
        /// </summary>
        internal static string user_blank {
            get {
                return ResourceManager.GetString("user_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok hızlı ve kolay e-posta gönderin! .....
        /// </summary>
        internal static string user_email {
            get {
                return ResourceManager.GetString("user_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir hesap oluşturun ve kullanıcı adınız ile her zaman giriş yapın. . . ..
        /// </summary>
        internal static string user_konto {
            get {
                return ResourceManager.GetString("user_konto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınızı daha sonra kullanmak için fiş / kupon satın alarak mevcut hesabınıza yükleme yapabilirsiniz! . . ..
        /// </summary>
        internal static string user_konto_aufladen {
            get {
                return ResourceManager.GetString("user_konto_aufladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok hızlı ve ucuz sabit hat veya mobil cihazlar için bir arama yapın! . . ..
        /// </summary>
        internal static string user_phone {
            get {
                return ResourceManager.GetString("user_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok ucuza SMS-Yolla! Çok hızlı, kolay ve cep telefonlarından daha ucuz!.
        /// </summary>
        internal static string user_sms {
            get {
                return ResourceManager.GetString("user_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat dilimi kontrol ediliyor....
        /// </summary>
        internal static string zeitZone {
            get {
                return ResourceManager.GetString("zeitZone", resourceCulture);
            }
        }
    }
}
