//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kioskplus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class kioskplusen_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal kioskplusen_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kioskplus.kioskplusen-US", typeof(kioskplusen_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields marked with * are required fields..
        /// </summary>
        internal static string allgEingabeError {
            get {
                return ResourceManager.GetString("allgEingabeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your Network and Internet-Connection.
        /// </summary>
        internal static string allgInternetError {
            get {
                return ResourceManager.GetString("allgInternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking data.....
        /// </summary>
        internal static string aufladenMsg {
            get {
                return ResourceManager.GetString("aufladenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no acceptor found, please check your configuration..
        /// </summary>
        internal static string billErrorFound {
            get {
                return ResourceManager.GetString("billErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptor found, please finish your configuration..
        /// </summary>
        internal static string billSuccessFound {
            get {
                return ResourceManager.GetString("billSuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait . . ..
        /// </summary>
        internal static string bittewarten {
            get {
                return ResourceManager.GetString("bittewarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS sending... Please wait....
        /// </summary>
        internal static string bittewartenSMS {
            get {
                return ResourceManager.GetString("bittewartenSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string blackDoppeln {
            get {
                return ResourceManager.GetString("blackDoppeln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double not possible, {0} your credit is not enough! {1} Please insert a coin..
        /// </summary>
        internal static string blackDoppelnError {
            get {
                return ResourceManager.GetString("blackDoppelnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your commitment: {0}.
        /// </summary>
        internal static string blackEinsatz {
            get {
                return ResourceManager.GetString("blackEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete commitment.
        /// </summary>
        internal static string blackEinsatzDelete {
            get {
                return ResourceManager.GetString("blackEinsatzDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Enter your commitment.
        /// </summary>
        internal static string blackErrorEinsatz {
            get {
                return ResourceManager.GetString("blackErrorEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won.
        /// </summary>
        internal static string blackGewonnen {
            get {
                return ResourceManager.GetString("blackGewonnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        internal static string blackKVerloren {
            get {
                return ResourceManager.GetString("blackKVerloren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Commitment: {0}.
        /// </summary>
        internal static string blackMaxEinsatz {
            get {
                return ResourceManager.GetString("blackMaxEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Max. commitment exceeded.
        /// </summary>
        internal static string blackMaxEinsatzUeber {
            get {
                return ResourceManager.GetString("blackMaxEinsatzUeber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string blackNehmen {
            get {
                return ResourceManager.GetString("blackNehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        internal static string blackSplitten {
            get {
                return ResourceManager.GetString("blackSplitten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split not possible,{0} your credit is not enough! {1}Please insert a coin..
        /// </summary>
        internal static string blackSplittenError {
            get {
                return ResourceManager.GetString("blackSplittenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stand.
        /// </summary>
        internal static string blackStehen {
            get {
                return ResourceManager.GetString("blackStehen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stand-off.
        /// </summary>
        internal static string blackUnentschieden {
            get {
                return ResourceManager.GetString("blackUnentschieden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost.
        /// </summary>
        internal static string blackVerloren {
            get {
                return ResourceManager.GetString("blackVerloren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance?.
        /// </summary>
        internal static string blackVersichern {
            get {
                return ResourceManager.GetString("blackVersichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        internal static string blackWeiter {
            get {
                return ResourceManager.GetString("blackWeiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This KIOSK-ID was deactivated!.
        /// </summary>
        internal static string blockedID {
            get {
                return ResourceManager.GetString("blockedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnBeenden {
            get {
                return ResourceManager.GetString("btnBeenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action has been cancelled.
        /// </summary>
        internal static string cancelLicenceAction {
            get {
                return ResourceManager.GetString("cancelLicenceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking data.....
        /// </summary>
        internal static string checkData {
            get {
                return ResourceManager.GetString("checkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for release....
        /// </summary>
        internal static string checkFreigabe {
            get {
                return ResourceManager.GetString("checkFreigabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking your KIOSK-ID.
        /// </summary>
        internal static string checkID {
            get {
                return ResourceManager.GetString("checkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the site!.
        /// </summary>
        internal static string checkSperrSeite {
            get {
                return ResourceManager.GetString("checkSperrSeite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closing kioskplus.
        /// </summary>
        internal static string closeApp {
            get {
                return ResourceManager.GetString("closeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of User Accounts deactivated at this terminal.
        /// </summary>
        internal static string deaktivKontoAnlegen {
            get {
                return ResourceManager.GetString("deaktivKontoAnlegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging of User Accounts deactivated at this terminal.
        /// </summary>
        internal static string deaktivKontoAufladen {
            get {
                return ResourceManager.GetString("deaktivKontoAufladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files|*.*.
        /// </summary>
        internal static string dlgFileExtension {
            get {
                return ResourceManager.GetString("dlgFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a File.
        /// </summary>
        internal static string dlgFileTitle {
            get {
                return ResourceManager.GetString("dlgFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong input.
        /// </summary>
        internal static string errorAufladenEingabe {
            get {
                return ResourceManager.GetString("errorAufladenEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid character.
        /// </summary>
        internal static string errorAufladenInvalidCharachter {
            get {
                return ResourceManager.GetString("errorAufladenInvalidCharachter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your remainder time must be {0] minute .....
        /// </summary>
        internal static string errorAufladenNoMinute {
            get {
                return ResourceManager.GetString("errorAufladenNoMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the phone number!.
        /// </summary>
        internal static string errorCheckTelNr {
            get {
                return ResourceManager.GetString("errorCheckTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Country!.
        /// </summary>
        internal static string errorChooseLand {
            get {
                return ResourceManager.GetString("errorChooseLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the phone number!.
        /// </summary>
        internal static string errorChooseTelNr {
            get {
                return ResourceManager.GetString("errorChooseTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sufficient Credit.
        /// </summary>
        internal static string errorDruckenGuthaben {
            get {
                return ResourceManager.GetString("errorDruckenGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured, when sending E-Mail.
        /// </summary>
        internal static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Email-Address!.
        /// </summary>
        internal static string errorEmailAdress {
            get {
                return ResourceManager.GetString("errorEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-Service now not available.
        /// </summary>
        internal static string errorEmailService {
            get {
                return ResourceManager.GetString("errorEmailService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your valid password!.
        /// </summary>
        internal static string errorFalschPwd {
            get {
                return ResourceManager.GetString("errorFalschPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your interest.
        /// </summary>
        internal static string errorhobby {
            get {
                return ResourceManager.GetString("errorhobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character entered ( {0} ).
        /// </summary>
        internal static string errorInValid {
            get {
                return ResourceManager.GetString("errorInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid KIOSK-ID .
        /// </summary>
        internal static string errorInvalidID {
            get {
                return ResourceManager.GetString("errorInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Characters (&amp;=&apos;) in your message.
        /// </summary>
        internal static string errorInvalidNachricht {
            get {
                return ResourceManager.GetString("errorInvalidNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your customer number is invalid. Please give your customer number..
        /// </summary>
        internal static string errorKdNr {
            get {
                return ResourceManager.GetString("errorKdNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid KIOSK-ID or invalid Password!.
        /// </summary>
        internal static string errorKioskIDorPwd {
            get {
                return ResourceManager.GetString("errorKioskIDorPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select coin Acceptor or set &apos;Com-Port&apos; to &apos;OFF&apos;.
        /// </summary>
        internal static string errorMP {
            get {
                return ResourceManager.GetString("errorMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select COM-Port where coin Acceptor is installed or set &apos;Com-Port&apos; to &apos;OFF&apos;.
        /// </summary>
        internal static string errorMPComPort {
            get {
                return ResourceManager.GetString("errorMPComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your surname!.
        /// </summary>
        internal static string errorName {
            get {
                return ResourceManager.GetString("errorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your valid password!.
        /// </summary>
        internal static string errorNewPwdEingabe {
            get {
                return ResourceManager.GetString("errorNewPwdEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username (Nickname) !.
        /// </summary>
        internal static string errorNickname {
            get {
                return ResourceManager.GetString("errorNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your message!.
        /// </summary>
        internal static string errorNoNachricht {
            get {
                return ResourceManager.GetString("errorNoNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the price !.
        /// </summary>
        internal static string errorPreis {
            get {
                return ResourceManager.GetString("errorPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct your repeated password!.
        /// </summary>
        internal static string errorPwdAgain {
            get {
                return ResourceManager.GetString("errorPwdAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password !.
        /// </summary>
        internal static string errorPwdEingabe {
            get {
                return ResourceManager.GetString("errorPwdEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS-Shipping not activated for this terminal.
        /// </summary>
        internal static string errorSmsDeaktiv {
            get {
                return ResourceManager.GetString("errorSmsDeaktiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credit time is not enough !.
        /// </summary>
        internal static string errorSMSZeitGuthaben {
            get {
                return ResourceManager.GetString("errorSMSZeitGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name!.
        /// </summary>
        internal static string errorVorname {
            get {
                return ResourceManager.GetString("errorVorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct your area code!.
        /// </summary>
        internal static string errorVorwahl {
            get {
                return ResourceManager.GetString("errorVorwahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your area code!.
        /// </summary>
        internal static string errorVorwahlEingabe {
            get {
                return ResourceManager.GetString("errorVorwahlEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam not found.
        /// </summary>
        internal static string errorWebCam {
            get {
                return ResourceManager.GetString("errorWebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill instances.
        /// </summary>
        internal static string fillinstance {
            get {
                return ResourceManager.GetString("fillinstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.....
        /// </summary>
        internal static string freigabeDurch {
            get {
                return ResourceManager.GetString("freigabeDurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking ....
        /// </summary>
        internal static string freigabePruef {
            get {
                return ResourceManager.GetString("freigabePruef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releasing terminal....
        /// </summary>
        internal static string freigabeTerminal {
            get {
                return ResourceManager.GetString("freigabeTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have created the following Kiosk-Id for you. {0} Your passwort for this Kiosk-ID is &quot;inetplus&quot;.{1}Your Kiosk-ID:{2}.
        /// </summary>
        internal static string getfreelicence {
            get {
                return ResourceManager.GetString("getfreelicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation not completed. Please refresh your installation..
        /// </summary>
        internal static string incompleteInstall {
            get {
                return ResourceManager.GetString("incompleteInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | active.
        /// </summary>
        internal static string infoActive {
            get {
                return ResourceManager.GetString("infoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Acceptor.
        /// </summary>
        internal static string infoBill {
            get {
                return ResourceManager.GetString("infoBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | not active.
        /// </summary>
        internal static string infoDeactive {
            get {
                return ResourceManager.GetString("infoDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}.
        /// </summary>
        internal static string infoErrorEnde {
            get {
                return ResourceManager.GetString("infoErrorEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string infoGames {
            get {
                return ResourceManager.GetString("infoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string infoIkunden {
            get {
                return ResourceManager.GetString("infoIkunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Acceptor.
        /// </summary>
        internal static string infoMP {
            get {
                return ResourceManager.GetString("infoMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Acceptor and Bill Acceptor.
        /// </summary>
        internal static string infoMPBill {
            get {
                return ResourceManager.GetString("infoMPBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS-Shipping.
        /// </summary>
        internal static string infoSMS {
            get {
                return ResourceManager.GetString("infoSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully.
        /// </summary>
        internal static string infoSuccessEnde {
            get {
                return ResourceManager.GetString("infoSuccessEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling.
        /// </summary>
        internal static string infoVoip {
            get {
                return ResourceManager.GetString("infoVoip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Input.
        /// </summary>
        internal static string kpc1 {
            get {
                return ResourceManager.GetString("kpc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon is disabled !.
        /// </summary>
        internal static string kpc10 {
            get {
                return ResourceManager.GetString("kpc10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon was already used !.
        /// </summary>
        internal static string kpc11 {
            get {
                return ResourceManager.GetString("kpc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free licence supported in your country. Would you like to use licence with cost?.
        /// </summary>
        internal static string kpc112 {
            get {
                return ResourceManager.GetString("kpc112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general error has occured! Please try again later..
        /// </summary>
        internal static string kpc113 {
            get {
                return ResourceManager.GetString("kpc113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your customer number or password is wrong. Please re-type your customer number and password..
        /// </summary>
        internal static string kpc114 {
            get {
                return ResourceManager.GetString("kpc114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is invalid.
        /// </summary>
        internal static string kpc12 {
            get {
                return ResourceManager.GetString("kpc12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not rechargeable Coupon. only possible for login!.
        /// </summary>
        internal static string kpc13 {
            get {
                return ResourceManager.GetString("kpc13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Version only after Registering installable. Please contact us at support@inetplus.de..
        /// </summary>
        internal static string kpc14 {
            get {
                return ResourceManager.GetString("kpc14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid KIOSK-ID or invalid Password ! .
        /// </summary>
        internal static string kpc15 {
            get {
                return ResourceManager.GetString("kpc15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This KIOSK-ID is disabled !.
        /// </summary>
        internal static string kpc16 {
            get {
                return ResourceManager.GetString("kpc16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS contingent is not enough..
        /// </summary>
        internal static string kpc17 {
            get {
                return ResourceManager.GetString("kpc17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Credit is not enough..
        /// </summary>
        internal static string kpc18 {
            get {
                return ResourceManager.GetString("kpc18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already used.
        /// </summary>
        internal static string kpc19 {
            get {
                return ResourceManager.GetString("kpc19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged in .
        /// </summary>
        internal static string kpc2 {
            get {
                return ResourceManager.GetString("kpc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the KIOSK-ID will be blocked with the next incorrectly entered!.
        /// </summary>
        internal static string kpc20 {
            get {
                return ResourceManager.GetString("kpc20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid password.
        /// </summary>
        internal static string kpc3 {
            get {
                return ResourceManager.GetString("kpc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid location.
        /// </summary>
        internal static string kpc4 {
            get {
                return ResourceManager.GetString("kpc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account is disabled.
        /// </summary>
        internal static string kpc5 {
            get {
                return ResourceManager.GetString("kpc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account was deleted.
        /// </summary>
        internal static string kpc6 {
            get {
                return ResourceManager.GetString("kpc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account is empty.Please recharge .
        /// </summary>
        internal static string kpc7 {
            get {
                return ResourceManager.GetString("kpc7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid location (Share)!.
        /// </summary>
        internal static string kpc8 {
            get {
                return ResourceManager.GetString("kpc8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in !.
        /// </summary>
        internal static string kpc9 {
            get {
                return ResourceManager.GetString("kpc9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your terminal will be shortly.
        /// </summary>
        internal static string last1Minuten {
            get {
                return ResourceManager.GetString("last1Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your terminal will be blocked. Please be ready in 119 . . 177 . . 115.
        /// </summary>
        internal static string last2Minuten {
            get {
                return ResourceManager.GetString("last2Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string last3Minuten {
            get {
                return ResourceManager.GetString("last3Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after that your terminal will be blocked..
        /// </summary>
        internal static string last4Minuten {
            get {
                return ResourceManager.GetString("last4Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after that your terminal will be blocked. Please remember a timely extension..
        /// </summary>
        internal static string last5Minuten {
            get {
                return ResourceManager.GetString("last5Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have only {0} minutes . ..
        /// </summary>
        internal static string lastMinutenNoch {
            get {
                return ResourceManager.GetString("lastMinutenNoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Connection.
        /// </summary>
        internal static string menu01 {
            get {
                return ResourceManager.GetString("menu01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string menu02 {
            get {
                return ResourceManager.GetString("menu02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit terminal.
        /// </summary>
        internal static string menu03 {
            get {
                return ResourceManager.GetString("menu03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inetplus Agent change.
        /// </summary>
        internal static string menu04 {
            get {
                return ResourceManager.GetString("menu04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inetplus Agent deactivate.
        /// </summary>
        internal static string menu05 {
            get {
                return ResourceManager.GetString("menu05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inetplus Agent activate.
        /// </summary>
        internal static string menu052 {
            get {
                return ResourceManager.GetString("menu052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack.
        /// </summary>
        internal static string menu06 {
            get {
                return ResourceManager.GetString("menu06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send photo.
        /// </summary>
        internal static string menu07 {
            get {
                return ResourceManager.GetString("menu07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string menu08 {
            get {
                return ResourceManager.GetString("menu08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coin acceptor found, please check your configuration.
        /// </summary>
        internal static string mpErrorFound {
            get {
                return ResourceManager.GetString("mpErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Acceptor not found. Please check your configuration.
        /// </summary>
        internal static string mpErrorFoundII {
            get {
                return ResourceManager.GetString("mpErrorFoundII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected coin Acceptor not supported. Error-Code: 00H3F47.
        /// </summary>
        internal static string mpFoundFalse {
            get {
                return ResourceManager.GetString("mpFoundFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Acceptor found. Please configure them.
        /// </summary>
        internal static string mpSuccessFound {
            get {
                return ResourceManager.GetString("mpSuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kioskplus will be restarted! Please click &apos;OK&apos; to continue.
        /// </summary>
        internal static string msgAppNeuStart {
            get {
                return ResourceManager.GetString("msgAppNeuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer is now restarted, so that fully functions can be activated ! {0} Please enter  &apos;OK&apos; to continue.
        /// </summary>
        internal static string msgPCNeuStart {
            get {
                return ResourceManager.GetString("msgPCNeuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0} . . . I am Agent {1}.
        /// </summary>
        internal static string newAgent {
            get {
                return ResourceManager.GetString("newAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t insert coins. restart in 5 seconds!.
        /// </summary>
        internal static string noMoneyInsert {
            get {
                return ResourceManager.GetString("noMoneyInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading objects....
        /// </summary>
        internal static string objLaden {
            get {
                return ResourceManager.GetString("objLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online-Update (Step &gt;&gt; {0} &lt;&lt; ).
        /// </summary>
        internal static string onlineUpd {
            get {
                return ResourceManager.GetString("onlineUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string portAus {
            get {
                return ResourceManager.GetString("portAus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per hour:.
        /// </summary>
        internal static string preisTitle {
            get {
                return ResourceManager.GetString("preisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one SMS costs {0} min(={1}  {2}).
        /// </summary>
        internal static string proSMSKostet {
            get {
                return ResourceManager.GetString("proSMSKostet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading Boot-Settings.
        /// </summary>
        internal static string readBootProperty {
            get {
                return ResourceManager.GetString("readBootProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading GUID-Data....
        /// </summary>
        internal static string readGUID {
            get {
                return ResourceManager.GetString("readGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading data from Customer Center....
        /// </summary>
        internal static string readKC {
            get {
                return ResourceManager.GetString("readKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading prices from Customer Center....
        /// </summary>
        internal static string readKCPreis {
            get {
                return ResourceManager.GetString("readKCPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading Printer-Price....
        /// </summary>
        internal static string readKCPrint {
            get {
                return ResourceManager.GetString("readKCPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading prices and shortcuts....
        /// </summary>
        internal static string readKeyAndPrise {
            get {
                return ResourceManager.GetString("readKeyAndPrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading protection of children and young people -Settings.
        /// </summary>
        internal static string readProtectOfMinor {
            get {
                return ResourceManager.GetString("readProtectOfMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait! Establishing connection . . ..
        /// </summary>
        internal static string sipBitteWarten {
            get {
                return ResourceManager.GetString("sipBitteWarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call terminates.....
        /// </summary>
        internal static string sipCallingEnde {
            get {
                return ResourceManager.GetString("sipCallingEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling number . . ..
        /// </summary>
        internal static string sipCallingNumber {
            get {
                return ResourceManager.GetString("sipCallingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP communication port could not be opened.
        /// </summary>
        internal static string sipCommError {
            get {
                return ResourceManager.GetString("sipCommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected. Please click the button to dial..
        /// </summary>
        internal static string sipError10 {
            get {
                return ResourceManager.GetString("sipError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callingport is busy.
        /// </summary>
        internal static string sipError11 {
            get {
                return ResourceManager.GetString("sipError11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence error occured.
        /// </summary>
        internal static string sipError12 {
            get {
                return ResourceManager.GetString("sipError12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError13 {
            get {
                return ResourceManager.GetString("sipError13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputdevice Mikro not available or is used by another Application.
        /// </summary>
        internal static string sipError14 {
            get {
                return ResourceManager.GetString("sipError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice outputdevice not available or is blocked by another application.
        /// </summary>
        internal static string sipError15 {
            get {
                return ResourceManager.GetString("sipError15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputdevice Mikro not available.
        /// </summary>
        internal static string sipError16 {
            get {
                return ResourceManager.GetString("sipError16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice outputdevice not available.
        /// </summary>
        internal static string sipError17 {
            get {
                return ResourceManager.GetString("sipError17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice outputdevice supports no volume intensity.
        /// </summary>
        internal static string sipError18 {
            get {
                return ResourceManager.GetString("sipError18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice outputdevice supports no volume intensity.
        /// </summary>
        internal static string sipError19 {
            get {
                return ResourceManager.GetString("sipError19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording media initialization failed.
        /// </summary>
        internal static string sipError20 {
            get {
                return ResourceManager.GetString("sipError20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File in *.wav Format could not be opened.
        /// </summary>
        internal static string sipError21 {
            get {
                return ResourceManager.GetString("sipError21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing.
        /// </summary>
        internal static string sipError22 {
            get {
                return ResourceManager.GetString("sipError22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec not supported.
        /// </summary>
        internal static string sipError23 {
            get {
                return ResourceManager.GetString("sipError23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDP-Request could not be created.
        /// </summary>
        internal static string sipError24 {
            get {
                return ResourceManager.GetString("sipError24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError25 {
            get {
                return ResourceManager.GetString("sipError25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError26 {
            get {
                return ResourceManager.GetString("sipError26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError27 {
            get {
                return ResourceManager.GetString("sipError27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError28 {
            get {
                return ResourceManager.GetString("sipError28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError29 {
            get {
                return ResourceManager.GetString("sipError29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection (busy).
        /// </summary>
        internal static string sipError30 {
            get {
                return ResourceManager.GetString("sipError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError31 {
            get {
                return ResourceManager.GetString("sipError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError32 {
            get {
                return ResourceManager.GetString("sipError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError33 {
            get {
                return ResourceManager.GetString("sipError33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when initializing connection.
        /// </summary>
        internal static string sipError34 {
            get {
                return ResourceManager.GetString("sipError34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to read File in Format wav.
        /// </summary>
        internal static string sipError35 {
            get {
                return ResourceManager.GetString("sipError35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to write File in Format wav.
        /// </summary>
        internal static string sipError36 {
            get {
                return ResourceManager.GetString("sipError36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not supported File Format.
        /// </summary>
        internal static string sipError37 {
            get {
                return ResourceManager.GetString("sipError37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dialing data.
        /// </summary>
        internal static string sipErrorDaten {
            get {
                return ResourceManager.GetString("sipErrorDaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Credit has shortly used up!.
        /// </summary>
        internal static string sipErrorGuthaben {
            get {
                return ResourceManager.GetString("sipErrorGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid call number.
        /// </summary>
        internal static string sipErrorInvalidNr {
            get {
                return ResourceManager.GetString("sipErrorInvalidNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prices defined ! (EUR).
        /// </summary>
        internal static string sipErrorNoDefinePreis {
            get {
                return ResourceManager.GetString("sipErrorNoDefinePreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prices defined ! (Currency).
        /// </summary>
        internal static string sipErrorNoDefineWaehrung {
            get {
                return ResourceManager.GetString("sipErrorNoDefineWaehrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit used up !.
        /// </summary>
        internal static string sipErrorNoGuthaben {
            get {
                return ResourceManager.GetString("sipErrorNoGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not possible to find a unused port for establishing the connection..
        /// </summary>
        internal static string sipErrorPort {
            get {
                return ResourceManager.GetString("sipErrorPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid telephone number.
        /// </summary>
        internal static string sipErrorTelNr {
            get {
                return ResourceManager.GetString("sipErrorTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Credit has used up. Charging possible by http://www.kuncenter.de.
        /// </summary>
        internal static string sipKontoGuthaben {
            get {
                return ResourceManager.GetString("sipKontoGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling is deactivated at this terminal..
        /// </summary>
        internal static string sipNoAllow {
            get {
                return ResourceManager.GetString("sipNoAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call started !.
        /// </summary>
        internal static string sipStartCalling {
            get {
                return ResourceManager.GetString("sipStartCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully.
        /// </summary>
        internal static string sipSuccessEnde {
            get {
                return ResourceManager.GetString("sipSuccessEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time credit not enough. Please insert coin..
        /// </summary>
        internal static string sipZeitGuthaben {
            get {
                return ResourceManager.GetString("sipZeitGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fantastic, send free emails without registration. Send emails to your friends.
        /// </summary>
        internal static string skin1 {
            get {
                return ResourceManager.GetString("skin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a dream, create in three steps a user account and continue surfing with the remaining time.
        /// </summary>
        internal static string skin2 {
            get {
                return ResourceManager.GetString("skin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charge your existing account with new credit or with a coupon.
        /// </summary>
        internal static string skin3 {
            get {
                return ResourceManager.GetString("skin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just easy, you can send favourable SMS from this terminal. The Message is cheaper and more convenient than from phone.
        /// </summary>
        internal static string skin4 {
            get {
                return ResourceManager.GetString("skin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to leave us? I still wish you a pleasant day. (0) visit me again soon.
        /// </summary>
        internal static string skin5 {
            get {
                return ResourceManager.GetString("skin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can make cheap calls fixed line, mobile and abroad.
        /// </summary>
        internal static string skin6 {
            get {
                return ResourceManager.GetString("skin6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible to send {0} SMS .
        /// </summary>
        internal static string smsKonto {
            get {
                return ResourceManager.GetString("smsKonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noch nicht!!!!!!!!!!!!!!!!.
        /// </summary>
        internal static string smsLandListe {
            get {
                return ResourceManager.GetString("smsLandListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check successfull.
        /// </summary>
        internal static string successCheck {
            get {
                return ResourceManager.GetString("successCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected.
        /// </summary>
        internal static string successConnect {
            get {
                return ResourceManager.GetString("successConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail send successfull !.
        /// </summary>
        internal static string successEmail {
            get {
                return ResourceManager.GetString("successEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully!.
        /// </summary>
        internal static string successEnde {
            get {
                return ResourceManager.GetString("successEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer data saved with success.
        /// </summary>
        internal static string successSaveKD {
            get {
                return ResourceManager.GetString("successSaveKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SMS is successfully send..
        /// </summary>
        internal static string successSMS {
            get {
                return ResourceManager.GetString("successSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for internetconnection....
        /// </summary>
        internal static string sucheInternet {
            get {
                return ResourceManager.GetString("sucheInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no Support-ID available!.
        /// </summary>
        internal static string supportText {
            get {
                return ResourceManager.GetString("supportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . . ..
        /// </summary>
        internal static string user_blank {
            get {
                return ResourceManager.GetString("user_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email very fast and easy !.....
        /// </summary>
        internal static string user_email {
            get {
                return ResourceManager.GetString("user_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool! You can create an account and log in with your username  everytime . . . ..
        /// </summary>
        internal static string user_konto {
            get {
                return ResourceManager.GetString("user_konto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load your existing account to use it later OR buy voucher/coupon to load your account ! . . ..
        /// </summary>
        internal static string user_konto_aufladen {
            get {
                return ResourceManager.GetString("user_konto_aufladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a call to landline or mobile devices very fast and cheaper ! . . ..
        /// </summary>
        internal static string user_phone {
            get {
                return ResourceManager.GetString("user_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very cheap SMS-Transmission! Very fast, easy and cheaper than mobile device !.
        /// </summary>
        internal static string user_sms {
            get {
                return ResourceManager.GetString("user_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking time zone....
        /// </summary>
        internal static string zeitZone {
            get {
                return ResourceManager.GetString("zeitZone", resourceCulture);
            }
        }
    }
}
