//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kioskplus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class kioskplus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal kioskplus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kioskplus.kioskplus", typeof(kioskplus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle mit * versehenen Eingabefelder müssen ausgefüllt werden..
        /// </summary>
        internal static string allgEingabeError {
            get {
                return ResourceManager.GetString("allgEingabeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfen Sie bitte, ob eine Netzwerk-/Internet-Verbindung besteht.
        /// </summary>
        internal static string allgInternetError {
            get {
                return ResourceManager.GetString("allgInternetError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap aufladen {
            get {
                object obj = ResourceManager.GetObject("aufladen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten werden geprüft.....
        /// </summary>
        internal static string aufladenMsg {
            get {
                return ResourceManager.GetString("aufladenMsg", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap benutzer {
            get {
                object obj = ResourceManager.GetObject("benutzer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Akzeptor gefunden.Bitte überprüfen Sie Ihre Einstellungen..
        /// </summary>
        internal static string billErrorFound {
            get {
                return ResourceManager.GetString("billErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde ein Akzeptor gefunden. Bitte konfigurieren Sie diesen..
        /// </summary>
        internal static string billSuccessFound {
            get {
                return ResourceManager.GetString("billSuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte warten . . ..
        /// </summary>
        internal static string bittewarten {
            get {
                return ResourceManager.GetString("bittewarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre SMS wird gesendet. Bitte warten...
        /// </summary>
        internal static string bittewartenSMS {
            get {
                return ResourceManager.GetString("bittewartenSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppeln.
        /// </summary>
        internal static string blackDoppeln {
            get {
                return ResourceManager.GetString("blackDoppeln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppeln nicht möglich, {0} da Ihr Guthaben nicht ausreicht! {1} Bitte werfen Sie eine Münze nach.
        /// </summary>
        internal static string blackDoppelnError {
            get {
                return ResourceManager.GetString("blackDoppelnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Einsatz: {0}.
        /// </summary>
        internal static string blackEinsatz {
            get {
                return ResourceManager.GetString("blackEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einsatz löschen.
        /// </summary>
        internal static string blackEinsatzDelete {
            get {
                return ResourceManager.GetString("blackEinsatzDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Bitte Einsatz eingeben.
        /// </summary>
        internal static string blackErrorEinsatz {
            get {
                return ResourceManager.GetString("blackErrorEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben gewonnen.
        /// </summary>
        internal static string blackGewonnen {
            get {
                return ResourceManager.GetString("blackGewonnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verloren.
        /// </summary>
        internal static string blackKVerloren {
            get {
                return ResourceManager.GetString("blackKVerloren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Einsatz: {0}.
        /// </summary>
        internal static string blackMaxEinsatz {
            get {
                return ResourceManager.GetString("blackMaxEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}Max. Einsatz überschritten.
        /// </summary>
        internal static string blackMaxEinsatzUeber {
            get {
                return ResourceManager.GetString("blackMaxEinsatzUeber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nehmen.
        /// </summary>
        internal static string blackNehmen {
            get {
                return ResourceManager.GetString("blackNehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitten.
        /// </summary>
        internal static string blackSplitten {
            get {
                return ResourceManager.GetString("blackSplitten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitten nicht möglich,{0} da Ihr Guthaben nicht ausreicht! {1}Bitte werfen Sie eine Münze nach.
        /// </summary>
        internal static string blackSplittenError {
            get {
                return ResourceManager.GetString("blackSplittenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stehen.
        /// </summary>
        internal static string blackStehen {
            get {
                return ResourceManager.GetString("blackStehen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unentschieden.
        /// </summary>
        internal static string blackUnentschieden {
            get {
                return ResourceManager.GetString("blackUnentschieden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben verloren.
        /// </summary>
        internal static string blackVerloren {
            get {
                return ResourceManager.GetString("blackVerloren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie versichern?.
        /// </summary>
        internal static string blackVersichern {
            get {
                return ResourceManager.GetString("blackVersichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        internal static string blackWeiter {
            get {
                return ResourceManager.GetString("blackWeiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese KIOSK-ID wurde gesperrt!.
        /// </summary>
        internal static string blockedID {
            get {
                return ResourceManager.GetString("blockedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string btnBeenden {
            get {
                return ResourceManager.GetString("btnBeenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion wurde abgebrochen.
        /// </summary>
        internal static string cancelLicenceAction {
            get {
                return ResourceManager.GetString("cancelLicenceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten prüfen.....
        /// </summary>
        internal static string checkData {
            get {
                return ResourceManager.GetString("checkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe überprüfen....
        /// </summary>
        internal static string checkFreigabe {
            get {
                return ResourceManager.GetString("checkFreigabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Kiosk-ID....
        /// </summary>
        internal static string checkID {
            get {
                return ResourceManager.GetString("checkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sperrseite prüfen.
        /// </summary>
        internal static string checkSperrSeite {
            get {
                return ResourceManager.GetString("checkSperrSeite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beende Kioskplus.
        /// </summary>
        internal static string closeApp {
            get {
                return ResourceManager.GetString("closeApp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap daufladen {
            get {
                object obj = ResourceManager.GetObject("daufladen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dbenutzer {
            get {
                object obj = ResourceManager.GetObject("dbenutzer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlegen von Benutzerkonten ist für dieses Terminal deaktiv.
        /// </summary>
        internal static string deaktivKontoAnlegen {
            get {
                return ResourceManager.GetString("deaktivKontoAnlegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoaufladen ist für dieses Terminal deaktiv.
        /// </summary>
        internal static string deaktivKontoAufladen {
            get {
                return ResourceManager.GetString("deaktivKontoAufladen", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap dexit {
            get {
                object obj = ResourceManager.GetObject("dexit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dateien|*.*.
        /// </summary>
        internal static string dlgFileExtension {
            get {
                return ResourceManager.GetString("dlgFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie eine Datei aus.
        /// </summary>
        internal static string dlgFileTitle {
            get {
                return ResourceManager.GetString("dlgFileTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap dmail {
            get {
                object obj = ResourceManager.GetObject("dmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dmain {
            get {
                object obj = ResourceManager.GetObject("dmain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doppelt_normal {
            get {
                object obj = ResourceManager.GetObject("doppelt_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap doppelt_over {
            get {
                object obj = ResourceManager.GetObject("doppelt_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dsms {
            get {
                object obj = ResourceManager.GetObject("dsms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dtelefon {
            get {
                object obj = ResourceManager.GetObject("dtelefon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche Eingabe.
        /// </summary>
        internal static string errorAufladenEingabe {
            get {
                return ResourceManager.GetString("errorAufladenEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Zeichen.
        /// </summary>
        internal static string errorAufladenInvalidCharachter {
            get {
                return ResourceManager.GetString("errorAufladenInvalidCharachter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Restzeit muss mindestens {0} min betragen.....
        /// </summary>
        internal static string errorAufladenNoMinute {
            get {
                return ResourceManager.GetString("errorAufladenNoMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte korrigieren Sie die Telefonnummer!.
        /// </summary>
        internal static string errorCheckTelNr {
            get {
                return ResourceManager.GetString("errorCheckTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie ein Land aus!.
        /// </summary>
        internal static string errorChooseLand {
            get {
                return ResourceManager.GetString("errorChooseLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie die Telefonnummer ein!.
        /// </summary>
        internal static string errorChooseTelNr {
            get {
                return ResourceManager.GetString("errorChooseTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guthaben nicht ausreichend. Bitte aufladen!.
        /// </summary>
        internal static string errorDruckenGuthaben {
            get {
                return ResourceManager.GetString("errorDruckenGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Versenden der EMail ist ein Fehler aufgetreten..
        /// </summary>
        internal static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige EMail Adresse ein.
        /// </summary>
        internal static string errorEmailAdress {
            get {
                return ResourceManager.GetString("errorEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-Service ist zur Zeit deaktiv.
        /// </summary>
        internal static string errorEmailService {
            get {
                return ResourceManager.GetString("errorEmailService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihr richtiges Passwort ein!.
        /// </summary>
        internal static string errorFalschPwd {
            get {
                return ResourceManager.GetString("errorFalschPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wähle deine Interessen aus.
        /// </summary>
        internal static string errorhobby {
            get {
                return ResourceManager.GetString("errorhobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Zeichen angegeben ( {0} ).
        /// </summary>
        internal static string errorInValid {
            get {
                return ResourceManager.GetString("errorInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige KIOSK-ID .
        /// </summary>
        internal static string errorInvalidID {
            get {
                return ResourceManager.GetString("errorInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Nachricht enthält ungültige Sonderzeichen (&amp;=&apos;).
        /// </summary>
        internal static string errorInvalidNachricht {
            get {
                return ResourceManager.GetString("errorInvalidNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Kundennummer ist falsch. Bitte geben Sie Ihre Kundennummer ein..
        /// </summary>
        internal static string errorKdNr {
            get {
                return ResourceManager.GetString("errorKdNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige KIOSK-ID oder ungültiges Passwort!.
        /// </summary>
        internal static string errorKioskIDorPwd {
            get {
                return ResourceManager.GetString("errorKioskIDorPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie einen Münzprüfer aus oder setzen Sie &apos;Com-Port&apos; auf &apos;AUS&apos;.
        /// </summary>
        internal static string errorMP {
            get {
                return ResourceManager.GetString("errorMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie den Com-Port aus an dem der Münzprüfer angeschlossen ist oder setzen Sie &apos;Com-Port&apos; auf &apos;AUS&apos;.
        /// </summary>
        internal static string errorMPComPort {
            get {
                return ResourceManager.GetString("errorMPComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihren Namen ein!.
        /// </summary>
        internal static string errorName {
            get {
                return ResourceManager.GetString("errorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein neues Passwort an!.
        /// </summary>
        internal static string errorNewPwdEingabe {
            get {
                return ResourceManager.GetString("errorNewPwdEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Benutzernamen (Nick-Namen) ein!.
        /// </summary>
        internal static string errorNickname {
            get {
                return ResourceManager.GetString("errorNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte schreiben Sie Ihre Nachricht!.
        /// </summary>
        internal static string errorNoNachricht {
            get {
                return ResourceManager.GetString("errorNoNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Preise ein!.
        /// </summary>
        internal static string errorPreis {
            get {
                return ResourceManager.GetString("errorPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte korrigieren Sie die Passwort-Wiederholung!.
        /// </summary>
        internal static string errorPwdAgain {
            get {
                return ResourceManager.GetString("errorPwdAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihr Passwort ein!.
        /// </summary>
        internal static string errorPwdEingabe {
            get {
                return ResourceManager.GetString("errorPwdEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS-Versand ist für dieses Terminal deaktiv.
        /// </summary>
        internal static string errorSmsDeaktiv {
            get {
                return ResourceManager.GetString("errorSmsDeaktiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Zeitguthaben reicht nicht aus!.
        /// </summary>
        internal static string errorSMSZeitGuthaben {
            get {
                return ResourceManager.GetString("errorSMSZeitGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihren Vornamen ein!.
        /// </summary>
        internal static string errorVorname {
            get {
                return ResourceManager.GetString("errorVorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte korrigieren Sie die Vorwahl!.
        /// </summary>
        internal static string errorVorwahl {
            get {
                return ResourceManager.GetString("errorVorwahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie die Vorwahl ein!.
        /// </summary>
        internal static string errorVorwahlEingabe {
            get {
                return ResourceManager.GetString("errorVorwahlEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam nicht vorhanden.
        /// </summary>
        internal static string errorWebCam {
            get {
                return ResourceManager.GetString("errorWebCam", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit_over {
            get {
                object obj = ResourceManager.GetObject("exit_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instanzen füllen.
        /// </summary>
        internal static string fillinstance {
            get {
                return ResourceManager.GetString("fillinstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe durchführen.....
        /// </summary>
        internal static string freigabeDurch {
            get {
                return ResourceManager.GetString("freigabeDurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfung ....
        /// </summary>
        internal static string freigabePruef {
            get {
                return ResourceManager.GetString("freigabePruef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal wird freigegeben....
        /// </summary>
        internal static string freigabeTerminal {
            get {
                return ResourceManager.GetString("freigabeTerminal", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gb {
            get {
                object obj = ResourceManager.GetObject("gb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap geldscheine {
            get {
                object obj = ResourceManager.GetObject("geldscheine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap geldscheinpruefer {
            get {
                object obj = ResourceManager.GetObject("geldscheinpruefer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir haben für Sie folgende Kiosk-ID generiert.{0} Ihr Passwort für diese Kiosk-ID ist &quot;inetplus&quot;.{1}Ihre Kiosk-ID:{2}.
        /// </summary>
        internal static string getfreelicence {
            get {
                return ResourceManager.GetString("getfreelicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation nicht vollständig. Bitte aktualisieren Sie die Installation..
        /// </summary>
        internal static string incompleteInstall {
            get {
                return ResourceManager.GetString("incompleteInstall", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap inet_about {
            get {
                object obj = ResourceManager.GetObject("inet_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inet_blackjack {
            get {
                object obj = ResourceManager.GetObject("inet_blackjack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | aktiv.
        /// </summary>
        internal static string infoActive {
            get {
                return ResourceManager.GetString("infoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geldscheinleser.
        /// </summary>
        internal static string infoBill {
            get {
                return ResourceManager.GetString("infoBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | deaktiv.
        /// </summary>
        internal static string infoDeactive {
            get {
                return ResourceManager.GetString("infoDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler {0}.
        /// </summary>
        internal static string infoErrorEnde {
            get {
                return ResourceManager.GetString("infoErrorEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterhaltung.
        /// </summary>
        internal static string infoGames {
            get {
                return ResourceManager.GetString("infoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerkonten.
        /// </summary>
        internal static string infoIkunden {
            get {
                return ResourceManager.GetString("infoIkunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Münzprüfer.
        /// </summary>
        internal static string infoMP {
            get {
                return ResourceManager.GetString("infoMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Münzprüfer und Geldscheinleser.
        /// </summary>
        internal static string infoMPBill {
            get {
                return ResourceManager.GetString("infoMPBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS-Versand.
        /// </summary>
        internal static string infoSMS {
            get {
                return ResourceManager.GetString("infoSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich beendet.
        /// </summary>
        internal static string infoSuccessEnde {
            get {
                return ResourceManager.GetString("infoSuccessEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonieren.
        /// </summary>
        internal static string infoVoip {
            get {
                return ResourceManager.GetString("infoVoip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername existiert nicht, oder das Passwort ist falsch.
        /// </summary>
        internal static string kpc1 {
            get {
                return ResourceManager.GetString("kpc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon gesperrt !.
        /// </summary>
        internal static string kpc10 {
            get {
                return ResourceManager.GetString("kpc10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon bereits benutzt !.
        /// </summary>
        internal static string kpc11 {
            get {
                return ResourceManager.GetString("kpc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Ihrem Land werden keine Freie Lizenzen unterstützt. Möchten Sie kostenpflichtige Lizenzen benutzen?.
        /// </summary>
        internal static string kpc112 {
            get {
                return ResourceManager.GetString("kpc112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein allgemeiner Fehler ist aufgetreten. Bitte versuchen Sie später noch einmal..
        /// </summary>
        internal static string kpc113 {
            get {
                return ResourceManager.GetString("kpc113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Kundennummer oder Passwort ist falsch. Bitte geben Sie Ihre Daten erneut an..
        /// </summary>
        internal static string kpc114 {
            get {
                return ResourceManager.GetString("kpc114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ist ungültig.
        /// </summary>
        internal static string kpc12 {
            get {
                return ResourceManager.GetString("kpc12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht aufladbare Coupons. Nur Anmeldung möglich!.
        /// </summary>
        internal static string kpc13 {
            get {
                return ResourceManager.GetString("kpc13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Version nur nach Freischaltung möglich. Bitte an support@inetplus.de wenden..
        /// </summary>
        internal static string kpc14 {
            get {
                return ResourceManager.GetString("kpc14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige KIOSK-ID oder ungültiges Passwort !.
        /// </summary>
        internal static string kpc15 {
            get {
                return ResourceManager.GetString("kpc15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese KIOSK-ID ist gesperrt !.
        /// </summary>
        internal static string kpc16 {
            get {
                return ResourceManager.GetString("kpc16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Kontingent reicht nicht aus..
        /// </summary>
        internal static string kpc17 {
            get {
                return ResourceManager.GetString("kpc17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Zeit-Guthaben reicht nicht aus..
        /// </summary>
        internal static string kpc18 {
            get {
                return ResourceManager.GetString("kpc18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname ist bereits vergeben.
        /// </summary>
        internal static string kpc19 {
            get {
                return ResourceManager.GetString("kpc19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer ist bereits angemeldet.
        /// </summary>
        internal static string kpc2 {
            get {
                return ResourceManager.GetString("kpc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit der nächsten Falscheingabe wird die KIOSK-ID gesperrt!.
        /// </summary>
        internal static string kpc20 {
            get {
                return ResourceManager.GetString("kpc20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Passwort.
        /// </summary>
        internal static string kpc3 {
            get {
                return ResourceManager.GetString("kpc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Standort.
        /// </summary>
        internal static string kpc4 {
            get {
                return ResourceManager.GetString("kpc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerkonto ist gesperrt.
        /// </summary>
        internal static string kpc5 {
            get {
                return ResourceManager.GetString("kpc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerkonto ist gelöscht.
        /// </summary>
        internal static string kpc6 {
            get {
                return ResourceManager.GetString("kpc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Benutzerkonto ist leer. Um Ihr Benutzerkonto aufzuladen werfen Sie eine Münze ein und schreiben die Zeit Ihrem Benutzerkonto gut..
        /// </summary>
        internal static string kpc7 {
            get {
                return ResourceManager.GetString("kpc7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ungültiger Aufstellplatz (Share)!.
        /// </summary>
        internal static string kpc8 {
            get {
                return ResourceManager.GetString("kpc8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind bereits angemeldet !.
        /// </summary>
        internal static string kpc9 {
            get {
                return ResourceManager.GetString("kpc9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In wenigen Sekunden wird dein Terminal .
        /// </summary>
        internal static string last1Minuten {
            get {
                return ResourceManager.GetString("last1Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dein Terminal wird gesperrt. Bitte bereite dich vor 119 . . 117 . . 115.
        /// </summary>
        internal static string last2Minuten {
            get {
                return ResourceManager.GetString("last2Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wird knapp.
        /// </summary>
        internal static string last3Minuten {
            get {
                return ResourceManager.GetString("last3Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danach wird dein Terminal gesperrt..
        /// </summary>
        internal static string last4Minuten {
            get {
                return ResourceManager.GetString("last4Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danach wird dein Terminal gesperrt. Bitte denk an eine rechtzeitige Verlängerung.
        /// </summary>
        internal static string last5Minuten {
            get {
                return ResourceManager.GetString("last5Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast nur noch {0} Minuten . ..
        /// </summary>
        internal static string lastMinutenNoch {
            get {
                return ResourceManager.GetString("lastMinutenNoch", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap laufladen {
            get {
                object obj = ResourceManager.GetObject("laufladen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lbenutzer {
            get {
                object obj = ResourceManager.GetObject("lbenutzer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lexit {
            get {
                object obj = ResourceManager.GetObject("lexit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmail {
            get {
                object obj = ResourceManager.GetObject("lmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lmain {
            get {
                object obj = ResourceManager.GetObject("lmain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_kuncenter {
            get {
                object obj = ResourceManager.GetObject("logo_kuncenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lsms {
            get {
                object obj = ResourceManager.GetObject("lsms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ltelefon {
            get {
                object obj = ResourceManager.GetObject("ltelefon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail {
            get {
                object obj = ResourceManager.GetObject("mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maufladen {
            get {
                object obj = ResourceManager.GetObject("maufladen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mbenutzer {
            get {
                object obj = ResourceManager.GetObject("mbenutzer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Verbindung.
        /// </summary>
        internal static string menu01 {
            get {
                return ResourceManager.GetString("menu01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string menu02 {
            get {
                return ResourceManager.GetString("menu02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal beenden.
        /// </summary>
        internal static string menu03 {
            get {
                return ResourceManager.GetString("menu03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inetplus Agent austauschen.
        /// </summary>
        internal static string menu04 {
            get {
                return ResourceManager.GetString("menu04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inetplus Agent deaktivieren.
        /// </summary>
        internal static string menu05 {
            get {
                return ResourceManager.GetString("menu05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inetplus Agent aktivieren.
        /// </summary>
        internal static string menu052 {
            get {
                return ResourceManager.GetString("menu052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack.
        /// </summary>
        internal static string menu06 {
            get {
                return ResourceManager.GetString("menu06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto senden.
        /// </summary>
        internal static string menu07 {
            get {
                return ResourceManager.GetString("menu07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiele.
        /// </summary>
        internal static string menu08 {
            get {
                return ResourceManager.GetString("menu08", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mexit {
            get {
                object obj = ResourceManager.GetObject("mexit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mmail {
            get {
                object obj = ResourceManager.GetObject("mmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mmain {
            get {
                object obj = ResourceManager.GetObject("mmain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Münzprüfer gefunden.Bitte überprüfen Sie Ihre Einstellungen..
        /// </summary>
        internal static string mpErrorFound {
            get {
                return ResourceManager.GetString("mpErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der richtige Münzprüfer konnte nicht gefunden werden. Bitte überprüfen Sie die Einstellungen.
        /// </summary>
        internal static string mpErrorFoundII {
            get {
                return ResourceManager.GetString("mpErrorFoundII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angeschlossene Münzprüfer wird nicht unterstützt. Fehler-Code: 00H3F47.
        /// </summary>
        internal static string mpFoundFalse {
            get {
                return ResourceManager.GetString("mpFoundFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde ein Münzprüfer gefunden. Bitte konfigurieren Sie diesen..
        /// </summary>
        internal static string mpSuccessFound {
            get {
                return ResourceManager.GetString("mpSuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kioskplus muss neu gestartet werden! Bitte betätigen Sie &apos;OK&apos; zum Fortfahren.
        /// </summary>
        internal static string msgAppNeuStart {
            get {
                return ResourceManager.GetString("msgAppNeuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Computer wird jetzt neu gestartet, damit der gesamte Funktionsumfang aktiviert werden kann ! {0}Bitte betätigen Sie &apos;OK&apos; zum Fortfahren.
        /// </summary>
        internal static string msgPCNeuStart {
            get {
                return ResourceManager.GetString("msgPCNeuStart", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap msms {
            get {
                object obj = ResourceManager.GetObject("msms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mtelefon {
            get {
                object obj = ResourceManager.GetObject("mtelefon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap muennzpruefer {
            get {
                object obj = ResourceManager.GetObject("muennzpruefer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nehmen_normal {
            get {
                object obj = ResourceManager.GetObject("nehmen_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nehmen_over {
            get {
                object obj = ResourceManager.GetObject("nehmen_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo {0} . . . Ich bin Agent {1}.
        /// </summary>
        internal static string newAgent {
            get {
                return ResourceManager.GetString("newAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte werfen Sie keine Münze ein. Neustart erfolgt in 5 Sekunden!.
        /// </summary>
        internal static string noMoneyInsert {
            get {
                return ResourceManager.GetString("noMoneyInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekte laden....
        /// </summary>
        internal static string objLaden {
            get {
                return ResourceManager.GetString("objLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online-Update (Schritt &gt;&gt; {0} &lt;&lt; ).
        /// </summary>
        internal static string onlineUpd {
            get {
                return ResourceManager.GetString("onlineUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUS.
        /// </summary>
        internal static string portAus {
            get {
                return ResourceManager.GetString("portAus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunden-Preise:.
        /// </summary>
        internal static string preisTitle {
            get {
                return ResourceManager.GetString("preisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine SMS kostet Sie {0} min(={1}  {2}).
        /// </summary>
        internal static string proSMSKostet {
            get {
                return ResourceManager.GetString("proSMSKostet", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap raufladen {
            get {
                object obj = ResourceManager.GetObject("raufladen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rbaufladen {
            get {
                object obj = ResourceManager.GetObject("rbaufladen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rbbenutzer {
            get {
                object obj = ResourceManager.GetObject("rbbenutzer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rbenutzer {
            get {
                object obj = ResourceManager.GetObject("rbenutzer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rbexit {
            get {
                object obj = ResourceManager.GetObject("rbexit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rbmail {
            get {
                object obj = ResourceManager.GetObject("rbmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rbmain {
            get {
                object obj = ResourceManager.GetObject("rbmain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rbsms {
            get {
                object obj = ResourceManager.GetObject("rbsms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rbtelefon {
            get {
                object obj = ResourceManager.GetObject("rbtelefon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lese Boot-Einstellungen....
        /// </summary>
        internal static string readBootProperty {
            get {
                return ResourceManager.GetString("readBootProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID-Daten werden eingelesen....
        /// </summary>
        internal static string readGUID {
            get {
                return ResourceManager.GetString("readGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lese Kundencenterdaten....
        /// </summary>
        internal static string readKC {
            get {
                return ResourceManager.GetString("readKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lese Kundencenterpreise....
        /// </summary>
        internal static string readKCPreis {
            get {
                return ResourceManager.GetString("readKCPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lese Druck-Preise....
        /// </summary>
        internal static string readKCPrint {
            get {
                return ResourceManager.GetString("readKCPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasten und Preise lesen....
        /// </summary>
        internal static string readKeyAndPrise {
            get {
                return ResourceManager.GetString("readKeyAndPrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lese Jugendschutz-Einstellungen....
        /// </summary>
        internal static string readProtectOfMinor {
            get {
                return ResourceManager.GetString("readProtectOfMinor", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rexit {
            get {
                object obj = ResourceManager.GetObject("rexit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rmail {
            get {
                object obj = ResourceManager.GetObject("rmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rmain {
            get {
                object obj = ResourceManager.GetObject("rmain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rsms {
            get {
                object obj = ResourceManager.GetObject("rsms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rtelefon {
            get {
                object obj = ResourceManager.GetObject("rtelefon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ru {
            get {
                object obj = ResourceManager.GetObject("ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap schloss {
            get {
                object obj = ResourceManager.GetObject("schloss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_0 {
            get {
                object obj = ResourceManager.GetObject("sip_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_1 {
            get {
                object obj = ResourceManager.GetObject("sip_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_2 {
            get {
                object obj = ResourceManager.GetObject("sip_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_3 {
            get {
                object obj = ResourceManager.GetObject("sip_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_4 {
            get {
                object obj = ResourceManager.GetObject("sip_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_5 {
            get {
                object obj = ResourceManager.GetObject("sip_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_6 {
            get {
                object obj = ResourceManager.GetObject("sip_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_7 {
            get {
                object obj = ResourceManager.GetObject("sip_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_8 {
            get {
                object obj = ResourceManager.GetObject("sip_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_9 {
            get {
                object obj = ResourceManager.GetObject("sip_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_anfasser {
            get {
                object obj = ResourceManager.GetObject("sip_anfasser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_c {
            get {
                object obj = ResourceManager.GetObject("sip_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_del {
            get {
                object obj = ResourceManager.GetObject("sip_del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_iphone01 {
            get {
                object obj = ResourceManager.GetObject("sip_iphone01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_microphone_mute {
            get {
                object obj = ResourceManager.GetObject("sip_microphone_mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_microphone_on {
            get {
                object obj = ResourceManager.GetObject("sip_microphone_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_no {
            get {
                object obj = ResourceManager.GetObject("sip_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_regler_basis {
            get {
                object obj = ResourceManager.GetObject("sip_regler_basis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_regler_basis_h {
            get {
                object obj = ResourceManager.GetObject("sip_regler_basis_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_speaker_mute {
            get {
                object obj = ResourceManager.GetObject("sip_speaker_mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_speaker_on {
            get {
                object obj = ResourceManager.GetObject("sip_speaker_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sip_yes {
            get {
                object obj = ResourceManager.GetObject("sip_yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte warten! Verbindung wird aufgebaut . . ..
        /// </summary>
        internal static string sipBitteWarten {
            get {
                return ResourceManager.GetString("sipBitteWarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anruf beendet. . ..
        /// </summary>
        internal static string sipCallingEnde {
            get {
                return ResourceManager.GetString("sipCallingEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Nummer wird gewählt . . ..
        /// </summary>
        internal static string sipCallingNumber {
            get {
                return ResourceManager.GetString("sipCallingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP communication port kann nicht geöffnet werden..
        /// </summary>
        internal static string sipCommError {
            get {
                return ResourceManager.GetString("sipCommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind nicht angemeldet. Bitte betätigen Sie die Wahltaste..
        /// </summary>
        internal static string sipError10 {
            get {
                return ResourceManager.GetString("sipError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunikationsanschluss ist belegt.
        /// </summary>
        internal static string sipError11 {
            get {
                return ResourceManager.GetString("sipError11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizenzfehler ist aufgetreten.
        /// </summary>
        internal static string sipError12 {
            get {
                return ResourceManager.GetString("sipError12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError13 {
            get {
                return ResourceManager.GetString("sipError13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabegerät Mikrofon nicht verfügbar oder wird durch eine andere Anwendung verwendet.
        /// </summary>
        internal static string sipError14 {
            get {
                return ResourceManager.GetString("sipError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachausgabegerät nicht verfügbar oder wird durch eine andere Anwendung verwendet.
        /// </summary>
        internal static string sipError15 {
            get {
                return ResourceManager.GetString("sipError15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabegerät Mikrofon nicht verfügbar.
        /// </summary>
        internal static string sipError16 {
            get {
                return ResourceManager.GetString("sipError16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachausgabegerät nicht verfügbar.
        /// </summary>
        internal static string sipError17 {
            get {
                return ResourceManager.GetString("sipError17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachausgabegerät unterstützt keine Lautstärkeneinstellung.
        /// </summary>
        internal static string sipError18 {
            get {
                return ResourceManager.GetString("sipError18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachausgabegerät unterstützt keine Lautstärkeneinstellung.
        /// </summary>
        internal static string sipError19 {
            get {
                return ResourceManager.GetString("sipError19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme konnte nicht initialisiert werden.
        /// </summary>
        internal static string sipError20 {
            get {
                return ResourceManager.GetString("sipError20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei vom Format *.wav konnte nicht geöffnet werden.
        /// </summary>
        internal static string sipError21 {
            get {
                return ResourceManager.GetString("sipError21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisierung fehlgeschlagen.
        /// </summary>
        internal static string sipError22 {
            get {
                return ResourceManager.GetString("sipError22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec wird nicht unterstützt.
        /// </summary>
        internal static string sipError23 {
            get {
                return ResourceManager.GetString("sipError23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDP-Anfrage konnte nicht erstellt werden.
        /// </summary>
        internal static string sipError24 {
            get {
                return ResourceManager.GetString("sipError24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError25 {
            get {
                return ResourceManager.GetString("sipError25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError26 {
            get {
                return ResourceManager.GetString("sipError26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError27 {
            get {
                return ResourceManager.GetString("sipError27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError28 {
            get {
                return ResourceManager.GetString("sipError28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError29 {
            get {
                return ResourceManager.GetString("sipError29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung (besetzt).
        /// </summary>
        internal static string sipError30 {
            get {
                return ResourceManager.GetString("sipError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError31 {
            get {
                return ResourceManager.GetString("sipError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError32 {
            get {
                return ResourceManager.GetString("sipError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError33 {
            get {
                return ResourceManager.GetString("sipError33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim initialisieren der Telefonverbindung.
        /// </summary>
        internal static string sipError34 {
            get {
                return ResourceManager.GetString("sipError34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim lesen der Datei im Format wav.
        /// </summary>
        internal static string sipError35 {
            get {
                return ResourceManager.GetString("sipError35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim schreiben der Datei im Format wav.
        /// </summary>
        internal static string sipError36 {
            get {
                return ResourceManager.GetString("sipError36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht unterstütztes Dateiformat.
        /// </summary>
        internal static string sipError37 {
            get {
                return ResourceManager.GetString("sipError37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ungültige Verbindungsdaten.
        /// </summary>
        internal static string sipErrorDaten {
            get {
                return ResourceManager.GetString("sipErrorDaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Gesprächsguthaben ist in kürze aufgebraucht!.
        /// </summary>
        internal static string sipErrorGuthaben {
            get {
                return ResourceManager.GetString("sipErrorGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ungültige Rufnummer.
        /// </summary>
        internal static string sipErrorInvalidNr {
            get {
                return ResourceManager.GetString("sipErrorInvalidNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keine Preise definiert (EUR).
        /// </summary>
        internal static string sipErrorNoDefinePreis {
            get {
                return ResourceManager.GetString("sipErrorNoDefinePreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keine Preise definiert (Währung).
        /// </summary>
        internal static string sipErrorNoDefineWaehrung {
            get {
                return ResourceManager.GetString("sipErrorNoDefineWaehrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guthaben aufgebraucht !.
        /// </summary>
        internal static string sipErrorNoGuthaben {
            get {
                return ResourceManager.GetString("sipErrorNoGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist nicht möglich einen freien Port für die Kommunikation zu finden..
        /// </summary>
        internal static string sipErrorPort {
            get {
                return ResourceManager.GetString("sipErrorPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige Telefonnummer ein.
        /// </summary>
        internal static string sipErrorTelNr {
            get {
                return ResourceManager.GetString("sipErrorTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoguthaben leer, aufladen über Kuncenter möglich.
        /// </summary>
        internal static string sipKontoGuthaben {
            get {
                return ResourceManager.GetString("sipKontoGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonieren ist für dieses Terminal deaktiv..
        /// </summary>
        internal static string sipNoAllow {
            get {
                return ResourceManager.GetString("sipNoAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gespräch gestartet !.
        /// </summary>
        internal static string sipStartCalling {
            get {
                return ResourceManager.GetString("sipStartCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich beendet.
        /// </summary>
        internal static string sipSuccessEnde {
            get {
                return ResourceManager.GetString("sipSuccessEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitguthaben zu gering. Bitte Münze einwerfen..
        /// </summary>
        internal static string sipZeitGuthaben {
            get {
                return ResourceManager.GetString("sipZeitGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wahnsinn, kostenloser Email Versand ohne Anmeldung. Versende Emails an deine Freunde.
        /// </summary>
        internal static string skin1 {
            get {
                return ResourceManager.GetString("skin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfach Traumhaft, in drei Schritten ein Benutzerkonto anlegen und mit der Restzeit immer wieder surfen.
        /// </summary>
        internal static string skin2 {
            get {
                return ResourceManager.GetString("skin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade dein bestehendes Benutzerkonto mit neuem Guthaben oder mit einem Coupon auf..
        /// </summary>
        internal static string skin3 {
            get {
                return ResourceManager.GetString("skin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfach Super, du kannst von diesem Terminal aus sehr günstige SMS versenden. Der Versand ist günstiger und bequemer als vom Handy.
        /// </summary>
        internal static string skin4 {
            get {
                return ResourceManager.GetString("skin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du willst uns verlassen? Ich wünsche dir noch einen angenehmen Tag.{0} besuche mich bald wieder.
        /// </summary>
        internal static string skin5 {
            get {
                return ResourceManager.GetString("skin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst von diesem Terminal aus günstige Gespräche ins Festnetz, Handy und ins Ausland durchführen.
        /// </summary>
        internal static string skin6 {
            get {
                return ResourceManager.GetString("skin6", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sms {
            get {
                object obj = ResourceManager.GetObject("sms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es können noch {0} SMS versendet werden.
        /// </summary>
        internal static string smsKonto {
            get {
                return ResourceManager.GetString("smsKonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noch nicht!!.
        /// </summary>
        internal static string smsLandListe {
            get {
                return ResourceManager.GetString("smsLandListe", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap splitten_normal {
            get {
                object obj = ResourceManager.GetObject("splitten_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splitten_over {
            get {
                object obj = ResourceManager.GetObject("splitten_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stehen_normal {
            get {
                object obj = ResourceManager.GetObject("stehen_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stehen_over {
            get {
                object obj = ResourceManager.GetObject("stehen_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfung erfolgreich.
        /// </summary>
        internal static string successCheck {
            get {
                return ResourceManager.GetString("successCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung erfolgreich.
        /// </summary>
        internal static string successConnect {
            get {
                return ResourceManager.GetString("successConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email erfolgreich versendet !.
        /// </summary>
        internal static string successEmail {
            get {
                return ResourceManager.GetString("successEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich beendet!.
        /// </summary>
        internal static string successEnde {
            get {
                return ResourceManager.GetString("successEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundendaten erfolgreich gespeichert.
        /// </summary>
        internal static string successSaveKD {
            get {
                return ResourceManager.GetString("successSaveKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre SMS wurde erfolgreich versendet.
        /// </summary>
        internal static string successSMS {
            get {
                return ResourceManager.GetString("successSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche Internetverbindung....
        /// </summary>
        internal static string sucheInternet {
            get {
                return ResourceManager.GetString("sucheInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keine Support-ID hinterlegt!.
        /// </summary>
        internal static string supportText {
            get {
                return ResourceManager.GetString("supportText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap telefon {
            get {
                object obj = ResourceManager.GetObject("telefon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ti {
            get {
                object obj = ResourceManager.GetObject("ti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tr {
            get {
                object obj = ResourceManager.GetObject("tr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . . ..
        /// </summary>
        internal static string user_blank {
            get {
                return ResourceManager.GetString("user_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfach SUPER ! Kostenloser Email Versand ! Das war bisher nicht so einfach....!.
        /// </summary>
        internal static string user_email {
            get {
                return ResourceManager.GetString("user_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ist Cool ! Ein Konto anlegen und jederzeit mit deinem Nick-Namen und Passwort anmelden  . . . ..
        /// </summary>
        internal static string user_konto {
            get {
                return ResourceManager.GetString("user_konto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden Sie Ihr bestehendes Konto auf, um die Zeit später wieder verwenden zu können. ODER Erwerben Sie ein Coupon um Ihr Konto aufzuladen ! . . ..
        /// </summary>
        internal static string user_konto_aufladen {
            get {
                return ResourceManager.GetString("user_konto_aufladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wahnsinn, Bald können Sie von diesem Terminal aus telefonieren auf Festnetz, Handy, Ausland und das VIEL GÜNSTIGER als  normal ! . . ..
        /// </summary>
        internal static string user_phone {
            get {
                return ResourceManager.GetString("user_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super günstiger SMS-Versand! Schneller und Günstiger als vom Handy !.
        /// </summary>
        internal static string user_sms {
            get {
                return ResourceManager.GetString("user_sms", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap waufladen {
            get {
                object obj = ResourceManager.GetObject("waufladen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wbenutzer {
            get {
                object obj = ResourceManager.GetObject("wbenutzer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wdlgcam {
            get {
                object obj = ResourceManager.GetObject("wdlgcam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wdlgcam1 {
            get {
                object obj = ResourceManager.GetObject("wdlgcam1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wdrucken {
            get {
                object obj = ResourceManager.GetObject("wdrucken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap weiter_normal {
            get {
                object obj = ResourceManager.GetObject("weiter_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap weiter_over {
            get {
                object obj = ResourceManager.GetObject("weiter_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wemail {
            get {
                object obj = ResourceManager.GetObject("wemail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wsms {
            get {
                object obj = ResourceManager.GetObject("wsms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wsperren {
            get {
                object obj = ResourceManager.GetObject("wsperren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitzone wird geprüft....
        /// </summary>
        internal static string zeitZone {
            get {
                return ResourceManager.GetString("zeitZone", resourceCulture);
            }
        }
    }
}
