//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kioskplus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class kioskplusru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal kioskplusru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kioskplus.kioskplusru-RU", typeof(kioskplusru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Все что отмечено  *   является обязательным для заполнения..
        /// </summary>
        internal static string allgEingabeError {
            get {
                return ResourceManager.GetString("allgEingabeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, проверьте соединение с Интернета.
        /// </summary>
        internal static string allgInternetError {
            get {
                return ResourceManager.GetString("allgInternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные проверяются .....
        /// </summary>
        internal static string aufladenMsg {
            get {
                return ResourceManager.GetString("aufladenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банкнотоприемник не найден.Пожалуйста, проверьте свои настройки..
        /// </summary>
        internal static string billErrorFound {
            get {
                return ResourceManager.GetString("billErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банкнотоприемник найден. Пожалуйста, настройте его..
        /// </summary>
        internal static string billSuccessFound {
            get {
                return ResourceManager.GetString("billSuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите. . ..
        /// </summary>
        internal static string bittewarten {
            get {
                return ResourceManager.GetString("bittewarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши SMS  отправляються. Подождите ...
        /// </summary>
        internal static string bittewartenSMS {
            get {
                return ResourceManager.GetString("bittewartenSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удвоить.
        /// </summary>
        internal static string blackDoppeln {
            get {
                return ResourceManager.GetString("blackDoppeln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удвоить невозможно, {0}, так как вашего кредита не достаточно! {1} Пожалуйста, пополните ваш счёт.
        /// </summary>
        internal static string blackDoppelnError {
            get {
                return ResourceManager.GetString("blackDoppelnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша ставка: {0}.
        /// </summary>
        internal static string blackEinsatz {
            get {
                return ResourceManager.GetString("blackEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ставку удалить.
        /// </summary>
        internal static string blackEinsatzDelete {
            get {
                return ResourceManager.GetString("blackEinsatzDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Введите вашу Ставку.
        /// </summary>
        internal static string blackErrorEinsatz {
            get {
                return ResourceManager.GetString("blackErrorEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы выиграли.
        /// </summary>
        internal static string blackGewonnen {
            get {
                return ResourceManager.GetString("blackGewonnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы проиграли.
        /// </summary>
        internal static string blackKVerloren {
            get {
                return ResourceManager.GetString("blackKVerloren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная ставка: {0}.
        /// </summary>
        internal static string blackMaxEinsatz {
            get {
                return ResourceManager.GetString("blackMaxEinsatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Максимальная Ставка превышена.
        /// </summary>
        internal static string blackMaxEinsatzUeber {
            get {
                return ResourceManager.GetString("blackMaxEinsatzUeber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять.
        /// </summary>
        internal static string blackNehmen {
            get {
                return ResourceManager.GetString("blackNehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделить (split).
        /// </summary>
        internal static string blackSplitten {
            get {
                return ResourceManager.GetString("blackSplitten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделение (split) невозможено, {0}, так как вашего кредита не достаточно! {1} Пожалуйста, пополните ваш счёт.
        /// </summary>
        internal static string blackSplittenError {
            get {
                return ResourceManager.GetString("blackSplittenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановиться.
        /// </summary>
        internal static string blackStehen {
            get {
                return ResourceManager.GetString("blackStehen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничья.
        /// </summary>
        internal static string blackUnentschieden {
            get {
                return ResourceManager.GetString("blackUnentschieden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы проиграли.
        /// </summary>
        internal static string blackVerloren {
            get {
                return ResourceManager.GetString("blackVerloren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите застраховать?.
        /// </summary>
        internal static string blackVersichern {
            get {
                return ResourceManager.GetString("blackVersichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string blackWeiter {
            get {
                return ResourceManager.GetString("blackWeiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот Киоск-ID  заблокирован!.
        /// </summary>
        internal static string blockedID {
            get {
                return ResourceManager.GetString("blockedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закончить.
        /// </summary>
        internal static string btnBeenden {
            get {
                return ResourceManager.GetString("btnBeenden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие было остановлено..
        /// </summary>
        internal static string cancelLicenceAction {
            get {
                return ResourceManager.GetString("cancelLicenceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Данные проверяются .....
        /// </summary>
        internal static string checkData {
            get {
                return ResourceManager.GetString("checkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка лицензии....
        /// </summary>
        internal static string checkFreigabe {
            get {
                return ResourceManager.GetString("checkFreigabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить Киоск-ID ....
        /// </summary>
        internal static string checkID {
            get {
                return ResourceManager.GetString("checkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка маски.
        /// </summary>
        internal static string checkSperrSeite {
            get {
                return ResourceManager.GetString("checkSperrSeite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть Киоскплюс  .
        /// </summary>
        internal static string closeApp {
            get {
                return ResourceManager.GetString("closeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание учетной записи (счетов) пользователей на этом терминале выключено.
        /// </summary>
        internal static string deaktivKontoAnlegen {
            get {
                return ResourceManager.GetString("deaktivKontoAnlegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение счетов пользователей на этом терминале выключено.
        /// </summary>
        internal static string deaktivKontoAufladen {
            get {
                return ResourceManager.GetString("deaktivKontoAufladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы | *.*.
        /// </summary>
        internal static string dlgFileExtension {
            get {
                return ResourceManager.GetString("dlgFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите файл из.
        /// </summary>
        internal static string dlgFileTitle {
            get {
                return ResourceManager.GetString("dlgFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправилный набор.
        /// </summary>
        internal static string errorAufladenEingabe {
            get {
                return ResourceManager.GetString("errorAufladenEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимые символы.
        /// </summary>
        internal static string errorAufladenInvalidCharachter {
            get {
                return ResourceManager.GetString("errorAufladenInvalidCharachter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше оставшееся время должны быть, по крайней мере {0} мин .....
        /// </summary>
        internal static string errorAufladenNoMinute {
            get {
                return ResourceManager.GetString("errorAufladenNoMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите правильный номер телефона!.
        /// </summary>
        internal static string errorCheckTelNr {
            get {
                return ResourceManager.GetString("errorCheckTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите страну!.
        /// </summary>
        internal static string errorChooseLand {
            get {
                return ResourceManager.GetString("errorChooseLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите номер телефона!.
        /// </summary>
        internal static string errorChooseTelNr {
            get {
                return ResourceManager.GetString("errorChooseTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно. Пополните ваш счёт!.
        /// </summary>
        internal static string errorDruckenGuthaben {
            get {
                return ResourceManager.GetString("errorDruckenGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При отправке электронной почты произошла ошибка.
        /// </summary>
        internal static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите адрес электронной почты.
        /// </summary>
        internal static string errorEmailAdress {
            get {
                return ResourceManager.GetString("errorEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта в настоящее время выключена.
        /// </summary>
        internal static string errorEmailService {
            get {
                return ResourceManager.GetString("errorEmailService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просим указать Ваш правильный пароль!.
        /// </summary>
        internal static string errorFalschPwd {
            get {
                return ResourceManager.GetString("errorFalschPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите ваши интересы.
        /// </summary>
        internal static string errorhobby {
            get {
                return ResourceManager.GetString("errorhobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимые символы ({0}).
        /// </summary>
        internal static string errorInValid {
            get {
                return ResourceManager.GetString("errorInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный Киоск-ID.
        /// </summary>
        internal static string errorInvalidID {
            get {
                return ResourceManager.GetString("errorInvalidID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше сообщение содержит недопустимые символы (&amp;=&apos;).
        /// </summary>
        internal static string errorInvalidNachricht {
            get {
                return ResourceManager.GetString("errorInvalidNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш номер клиента это неправильно. Пожалуйста, введите Ваш номер клиента..
        /// </summary>
        internal static string errorKdNr {
            get {
                return ResourceManager.GetString("errorKdNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный Киоск-ID или пароль недействителен!.
        /// </summary>
        internal static string errorKioskIDorPwd {
            get {
                return ResourceManager.GetString("errorKioskIDorPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите монетоприёмник или добавьте &quot;COM-порт&quot; на &quot;Выкл&quot;.
        /// </summary>
        internal static string errorMP {
            get {
                return ResourceManager.GetString("errorMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите &quot;Com-порт&quot;, куда подключен монетоприёмник или добавьте &quot;COM-порт&quot; на &quot;Выкл&quot;.
        /// </summary>
        internal static string errorMPComPort {
            get {
                return ResourceManager.GetString("errorMPComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, укажите ваше имя!.
        /// </summary>
        internal static string errorName {
            get {
                return ResourceManager.GetString("errorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите новый пароль!.
        /// </summary>
        internal static string errorNewPwdEingabe {
            get {
                return ResourceManager.GetString("errorNewPwdEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите логин пользователя (ник имя)!.
        /// </summary>
        internal static string errorNickname {
            get {
                return ResourceManager.GetString("errorNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, напишите ваше сообщение!.
        /// </summary>
        internal static string errorNoNachricht {
            get {
                return ResourceManager.GetString("errorNoNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просьба указать цены!.
        /// </summary>
        internal static string errorPreis {
            get {
                return ResourceManager.GetString("errorPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите правильный пароль повторения!.
        /// </summary>
        internal static string errorPwdAgain {
            get {
                return ResourceManager.GetString("errorPwdAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите свой пароль!.
        /// </summary>
        internal static string errorPwdEingabe {
            get {
                return ResourceManager.GetString("errorPwdEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка SMS на терминале выключена.
        /// </summary>
        internal static string errorSmsDeaktiv {
            get {
                return ResourceManager.GetString("errorSmsDeaktiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно. Пополните ваш счёт!.
        /// </summary>
        internal static string errorSMSZeitGuthaben {
            get {
                return ResourceManager.GetString("errorSMSZeitGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите ваше имя!.
        /// </summary>
        internal static string errorVorname {
            get {
                return ResourceManager.GetString("errorVorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, исправьте код города!.
        /// </summary>
        internal static string errorVorwahl {
            get {
                return ResourceManager.GetString("errorVorwahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите код города!.
        /// </summary>
        internal static string errorVorwahlEingabe {
            get {
                return ResourceManager.GetString("errorVorwahlEingabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam не подлючена.
        /// </summary>
        internal static string errorWebCam {
            get {
                return ResourceManager.GetString("errorWebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните.
        /// </summary>
        internal static string fillinstance {
            get {
                return ResourceManager.GetString("fillinstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка Лицензии.....
        /// </summary>
        internal static string freigabeDurch {
            get {
                return ResourceManager.GetString("freigabeDurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка....
        /// </summary>
        internal static string freigabePruef {
            get {
                return ResourceManager.GetString("freigabePruef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка....
        /// </summary>
        internal static string freigabeTerminal {
            get {
                return ResourceManager.GetString("freigabeTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . У нас создан для следующих резервных ИД {0} пароль для этого резервный ИД &quot;inetplus&quot; {1} Ваш киоск ID. {2}.
        /// </summary>
        internal static string getfreelicence {
            get {
                return ResourceManager.GetString("getfreelicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка не завершена. Повторите установку..
        /// </summary>
        internal static string incompleteInstall {
            get {
                return ResourceManager.GetString("incompleteInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} |Вкл.
        /// </summary>
        internal static string infoActive {
            get {
                return ResourceManager.GetString("infoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банкнотоприемник.
        /// </summary>
        internal static string infoBill {
            get {
                return ResourceManager.GetString("infoBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | Выкл.
        /// </summary>
        internal static string infoDeactive {
            get {
                return ResourceManager.GetString("infoDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка {0}.
        /// </summary>
        internal static string infoErrorEnde {
            get {
                return ResourceManager.GetString("infoErrorEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развлечение.
        /// </summary>
        internal static string infoGames {
            get {
                return ResourceManager.GetString("infoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учетные записи пользователей.
        /// </summary>
        internal static string infoIkunden {
            get {
                return ResourceManager.GetString("infoIkunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монетоприёмник.
        /// </summary>
        internal static string infoMP {
            get {
                return ResourceManager.GetString("infoMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монетоприёмник и банкнотоприемник.
        /// </summary>
        internal static string infoMPBill {
            get {
                return ResourceManager.GetString("infoMPBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS-Отправка.
        /// </summary>
        internal static string infoSMS {
            get {
                return ResourceManager.GetString("infoSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно.
        /// </summary>
        internal static string infoSuccessEnde {
            get {
                return ResourceManager.GetString("infoSuccessEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звонить.
        /// </summary>
        internal static string infoVoip {
            get {
                return ResourceManager.GetString("infoVoip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный пароль или несуществующий логин.
        /// </summary>
        internal static string kpc1 {
            get {
                return ResourceManager.GetString("kpc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купона заблокированн!.
        /// </summary>
        internal static string kpc10 {
            get {
                return ResourceManager.GetString("kpc10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купон уже используется!.
        /// </summary>
        internal static string kpc11 {
            get {
                return ResourceManager.GetString("kpc11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В вашей стране нет свободных лицензий поддерживаются. Хотели бы Вы использовать платные лицензии?.
        /// </summary>
        internal static string kpc112 {
            get {
                return ResourceManager.GetString("kpc112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая ошибка. Пожалуйста, повторите попытку позже..
        /// </summary>
        internal static string kpc113 {
            get {
                return ResourceManager.GetString("kpc113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш номер клиента это неправильно. Пожалуйста, введите Ваш номер клиента Ваш номер клиента это неправильно. Пожалуйста, введите Ваш номер клиента снова..
        /// </summary>
        internal static string kpc114 {
            get {
                return ResourceManager.GetString("kpc114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недействительный.
        /// </summary>
        internal static string kpc12 {
            get {
                return ResourceManager.GetString("kpc12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не пополняемый купон. Возможен только вход!.
        /// </summary>
        internal static string kpc13 {
            get {
                return ResourceManager.GetString("kpc13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая версия только после обращения в inetplus возможна. Пожалуйста, свяжитесь с нами по адресу support@inetplus.de..
        /// </summary>
        internal static string kpc14 {
            get {
                return ResourceManager.GetString("kpc14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недействительный Киоск-ID или неверный пароль!.
        /// </summary>
        internal static string kpc15 {
            get {
                return ResourceManager.GetString("kpc15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот Киоск-ID заблокирован!.
        /// </summary>
        internal static string kpc16 {
            get {
                return ResourceManager.GetString("kpc16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS контингента недостаточно..
        /// </summary>
        internal static string kpc17 {
            get {
                return ResourceManager.GetString("kpc17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш кредит не достаточнен..
        /// </summary>
        internal static string kpc18 {
            get {
                return ResourceManager.GetString("kpc18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин уже используеться другим пользователем..
        /// </summary>
        internal static string kpc19 {
            get {
                return ResourceManager.GetString("kpc19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь уже зарегистрирован.
        /// </summary>
        internal static string kpc2 {
            get {
                return ResourceManager.GetString("kpc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последняя попытка, при неправильном  вводе  Киоск-ID будет заблокирован!.
        /// </summary>
        internal static string kpc20 {
            get {
                return ResourceManager.GetString("kpc20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неверный пароль.
        /// </summary>
        internal static string kpc3 {
            get {
                return ResourceManager.GetString("kpc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недействительное местоположение.
        /// </summary>
        internal static string kpc4 {
            get {
                return ResourceManager.GetString("kpc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to учетная запись пользователя(счёт) заблокирована.
        /// </summary>
        internal static string kpc5 {
            get {
                return ResourceManager.GetString("kpc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to учетная запись пользователя(счёт) была удалена.
        /// </summary>
        internal static string kpc6 {
            get {
                return ResourceManager.GetString("kpc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счёт пуст. Для пополнения счёта опустите монету в монетоприёмник и войдите на вашу учетную запись пользователя(счёт).
        /// </summary>
        internal static string kpc7 {
            get {
                return ResourceManager.GetString("kpc7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недействительное местоположение(Доля)!.
        /// </summary>
        internal static string kpc8 {
            get {
                return ResourceManager.GetString("kpc8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже вошли в систему!.
        /// </summary>
        internal static string kpc9 {
            get {
                return ResourceManager.GetString("kpc9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Через несколько секунд, Ваш терминал.
        /// </summary>
        internal static string last1Minuten {
            get {
                return ResourceManager.GetString("last1Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш терминал будет заблокирован. Пожалуйста, будьте готовы против 119. . 177. . 115.
        /// </summary>
        internal static string last2Minuten {
            get {
                return ResourceManager.GetString("last2Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это просто.
        /// </summary>
        internal static string last3Minuten {
            get {
                return ResourceManager.GetString("last3Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тогда ваш терминал заблокируется..
        /// </summary>
        internal static string last4Minuten {
            get {
                return ResourceManager.GetString("last4Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После чего ваш терминал будет заблокирован. Позаботесь о своевременном продление..
        /// </summary>
        internal static string last5Minuten {
            get {
                return ResourceManager.GetString("last5Minuten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас {0} минут. ..
        /// </summary>
        internal static string lastMinutenNoch {
            get {
                return ResourceManager.GetString("lastMinutenNoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка соединения.
        /// </summary>
        internal static string menu01 {
            get {
                return ResourceManager.GetString("menu01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string menu02 {
            get {
                return ResourceManager.GetString("menu02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string menu03 {
            get {
                return ResourceManager.GetString("menu03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to замена агента inetplus .
        /// </summary>
        internal static string menu04 {
            get {
                return ResourceManager.GetString("menu04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отключение агента inetplus .
        /// </summary>
        internal static string menu05 {
            get {
                return ResourceManager.GetString("menu05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to включение агента inetplus .
        /// </summary>
        internal static string menu052 {
            get {
                return ResourceManager.GetString("menu052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блэк Джек.
        /// </summary>
        internal static string menu06 {
            get {
                return ResourceManager.GetString("menu06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послать фотографию.
        /// </summary>
        internal static string menu07 {
            get {
                return ResourceManager.GetString("menu07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to матч.
        /// </summary>
        internal static string menu08 {
            get {
                return ResourceManager.GetString("menu08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монетоприёмник ненайден.Пожалуйста, проверьте настройки.
        /// </summary>
        internal static string mpErrorFound {
            get {
                return ResourceManager.GetString("mpErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужный монетоприёмник ненайден.Пожалуйста, проверьте настройки.
        /// </summary>
        internal static string mpErrorFoundII {
            get {
                return ResourceManager.GetString("mpErrorFoundII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монетоприёмник не поддерживается. Код ошибки: 00H3F47.
        /// </summary>
        internal static string mpFoundFalse {
            get {
                return ResourceManager.GetString("mpFoundFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монетоприёмник найден. Пожалуйста, настройте его..
        /// </summary>
        internal static string mpSuccessFound {
            get {
                return ResourceManager.GetString("mpSuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Киоскплюс  должен быть запущен еще раз! Нажмите кнопку &quot;OK&quot;, чтобы продолжить.
        /// </summary>
        internal static string msgAppNeuStart {
            get {
                return ResourceManager.GetString("msgAppNeuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сейчас компьютер перезагрузится, после чего весь спектр функций может быть активирован! {0} Пожалуйста, нажмите &quot;ОК&quot;, чтобы продолжить.
        /// </summary>
        internal static string msgPCNeuStart {
            get {
                return ResourceManager.GetString("msgPCNeuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет {0}. . . Я агент {1}.
        /// </summary>
        internal static string newAgent {
            get {
                return ResourceManager.GetString("newAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, не опускате монету. перезагрузка через 5 секунд!.
        /// </summary>
        internal static string noMoneyInsert {
            get {
                return ResourceManager.GetString("noMoneyInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты загрузить ....
        /// </summary>
        internal static string objLaden {
            get {
                return ResourceManager.GetString("objLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Update (шаг&gt;&gt; {0} &lt;&lt;).
        /// </summary>
        internal static string onlineUpd {
            get {
                return ResourceManager.GetString("onlineUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выкл.
        /// </summary>
        internal static string portAus {
            get {
                return ResourceManager.GetString("portAus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена за час:.
        /// </summary>
        internal static string preisTitle {
            get {
                return ResourceManager.GetString("preisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена SMS {0} мин (= {1} {2}).
        /// </summary>
        internal static string proSMSKostet {
            get {
                return ResourceManager.GetString("proSMSKostet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение загрузки настроек ....
        /// </summary>
        internal static string readBootProperty {
            get {
                return ResourceManager.GetString("readBootProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID данные будут импортироваться ....
        /// </summary>
        internal static string readGUID {
            get {
                return ResourceManager.GetString("readGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение  центра  управления....
        /// </summary>
        internal static string readKC {
            get {
                return ResourceManager.GetString("readKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение  цен центра  управления....
        /// </summary>
        internal static string readKCPreis {
            get {
                return ResourceManager.GetString("readKCPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение цен принтера....
        /// </summary>
        internal static string readKCPrint {
            get {
                return ResourceManager.GetString("readKCPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цены и кнопки чтении ....
        /// </summary>
        internal static string readKeyAndPrise {
            get {
                return ResourceManager.GetString("readKeyAndPrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение защите интересов молодежи настройки ....
        /// </summary>
        internal static string readProtectOfMinor {
            get {
                return ResourceManager.GetString("readProtectOfMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите! Соединение устанавливается. . ..
        /// </summary>
        internal static string sipBitteWarten {
            get {
                return ResourceManager.GetString("sipBitteWarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звонок закончился. . ..
        /// </summary>
        internal static string sipCallingEnde {
            get {
                return ResourceManager.GetString("sipCallingEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер набирается. . ..
        /// </summary>
        internal static string sipCallingNumber {
            get {
                return ResourceManager.GetString("sipCallingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP коммуникационного порта не может быть открыт..
        /// </summary>
        internal static string sipCommError {
            get {
                return ResourceManager.GetString("sipCommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не зарегистрированы. Пожалуйста, нажмите кнопку выборов..
        /// </summary>
        internal static string sipError10 {
            get {
                return ResourceManager.GetString("sipError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт сообщения занят.
        /// </summary>
        internal static string sipError11 {
            get {
                return ResourceManager.GetString("sipError11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка лицензии.
        /// </summary>
        internal static string sipError12 {
            get {
                return ResourceManager.GetString("sipError12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError13 {
            get {
                return ResourceManager.GetString("sipError13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Микрофон не доступен или исползуется другой программой.
        /// </summary>
        internal static string sipError14 {
            get {
                return ResourceManager.GetString("sipError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усилитель звука  не доступен или исползуется другой программой.
        /// </summary>
        internal static string sipError15 {
            get {
                return ResourceManager.GetString("sipError15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Микрофон не доступен.
        /// </summary>
        internal static string sipError16 {
            get {
                return ResourceManager.GetString("sipError16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усилитель звука не доступен.
        /// </summary>
        internal static string sipError17 {
            get {
                return ResourceManager.GetString("sipError17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усилитель звука не поддерживает объем настройки.
        /// </summary>
        internal static string sipError18 {
            get {
                return ResourceManager.GetString("sipError18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усилитель звука не поддерживает объем настройки.
        /// </summary>
        internal static string sipError19 {
            get {
                return ResourceManager.GetString("sipError19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись не может быть инициализирована.
        /// </summary>
        internal static string sipError20 {
            get {
                return ResourceManager.GetString("sipError20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл из формата *. wav  не может быть открыт.
        /// </summary>
        internal static string sipError21 {
            get {
                return ResourceManager.GetString("sipError21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка инициализации.
        /// </summary>
        internal static string sipError22 {
            get {
                return ResourceManager.GetString("sipError22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодек не поддерживается.
        /// </summary>
        internal static string sipError23 {
            get {
                return ResourceManager.GetString("sipError23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СДП запрос не может быть создано.
        /// </summary>
        internal static string sipError24 {
            get {
                return ResourceManager.GetString("sipError24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError25 {
            get {
                return ResourceManager.GetString("sipError25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError26 {
            get {
                return ResourceManager.GetString("sipError26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError27 {
            get {
                return ResourceManager.GetString("sipError27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError28 {
            get {
                return ResourceManager.GetString("sipError28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError29 {
            get {
                return ResourceManager.GetString("sipError29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи (занято).
        /// </summary>
        internal static string sipError30 {
            get {
                return ResourceManager.GetString("sipError30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError31 {
            get {
                return ResourceManager.GetString("sipError31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError32 {
            get {
                return ResourceManager.GetString("sipError32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError33 {
            get {
                return ResourceManager.GetString("sipError33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой при инициализации телефонной связи.
        /// </summary>
        internal static string sipError34 {
            get {
                return ResourceManager.GetString("sipError34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось прочитать файл в формате wav.
        /// </summary>
        internal static string sipError35 {
            get {
                return ResourceManager.GetString("sipError35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось записать файл в формате wav.
        /// </summary>
        internal static string sipError36 {
            get {
                return ResourceManager.GetString("sipError36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неподдерживаемый формат файла.
        /// </summary>
        internal static string sipError37 {
            get {
                return ResourceManager.GetString("sipError37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недействительные данные  соединения.
        /// </summary>
        internal static string sipErrorDaten {
            get {
                return ResourceManager.GetString("sipErrorDaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонный счёт скоро будет исчерпан!.
        /// </summary>
        internal static string sipErrorGuthaben {
            get {
                return ResourceManager.GetString("sipErrorGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недействительный телефонный номер.
        /// </summary>
        internal static string sipErrorInvalidNr {
            get {
                return ResourceManager.GetString("sipErrorInvalidNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена не определена (EUR).
        /// </summary>
        internal static string sipErrorNoDefinePreis {
            get {
                return ResourceManager.GetString("sipErrorNoDefinePreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена не определена (валюта).
        /// </summary>
        internal static string sipErrorNoDefineWaehrung {
            get {
                return ResourceManager.GetString("sipErrorNoDefineWaehrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонный счёт исчерпан!.
        /// </summary>
        internal static string sipErrorNoGuthaben {
            get {
                return ResourceManager.GetString("sipErrorNoGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно, найти свободный порт для коммуникации..
        /// </summary>
        internal static string sipErrorPort {
            get {
                return ResourceManager.GetString("sipErrorPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите действующий номер телефона.
        /// </summary>
        internal static string sipErrorTelNr {
            get {
                return ResourceManager.GetString("sipErrorTelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой телефонный счёт,пополнение  возможно в центре  управления.
        /// </summary>
        internal static string sipKontoGuthaben {
            get {
                return ResourceManager.GetString("sipKontoGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефония на этом терминале выключена..
        /// </summary>
        internal static string sipNoAllow {
            get {
                return ResourceManager.GetString("sipNoAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разговор начался!.
        /// </summary>
        internal static string sipStartCalling {
            get {
                return ResourceManager.GetString("sipStartCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно закончился.
        /// </summary>
        internal static string sipSuccessEnde {
            get {
                return ResourceManager.GetString("sipSuccessEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашего кредита не достаточно!  Пожалуйста, пополните ваш счёт..
        /// </summary>
        internal static string sipZeitGuthaben {
            get {
                return ResourceManager.GetString("sipZeitGuthaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фантастика, бесплатно отправлять электронную почту без регистрации. Отправить электронную почту вашим друзьям.
        /// </summary>
        internal static string skin1 {
            get {
                return ResourceManager.GetString("skin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просто мечта, создать в три этапа учетную запись пользователя, и использовать оставшееся время в следующий раз.
        /// </summary>
        internal static string skin2 {
            get {
                return ResourceManager.GetString("skin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополни существующую учетную запись деньгами или  купоном.
        /// </summary>
        internal static string skin3 {
            get {
                return ResourceManager.GetString("skin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просто класс! Вы можете отправить SMS с этого терминала. Сообщение удобнее и дешевле, чем с мобилы.
        /// </summary>
        internal static string skin4 {
            get {
                return ResourceManager.GetString("skin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите покинуть нас? Я желаю вам приятного дня. {0} Посетите нас снова.
        /// </summary>
        internal static string skin5 {
            get {
                return ResourceManager.GetString("skin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете дешево звонить на стационарные, мобильные и зарубежные телефоны.
        /// </summary>
        internal static string skin6 {
            get {
                return ResourceManager.GetString("skin6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ещё может быть {0} SMS отправлено .
        /// </summary>
        internal static string smsKonto {
            get {
                return ResourceManager.GetString("smsKonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ещё нет!.
        /// </summary>
        internal static string smsLandListe {
            get {
                return ResourceManager.GetString("smsLandListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка успешна.
        /// </summary>
        internal static string successCheck {
            get {
                return ResourceManager.GetString("successCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно подключен.
        /// </summary>
        internal static string successConnect {
            get {
                return ResourceManager.GetString("successConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронная почта успешно отправлена!.
        /// </summary>
        internal static string successEmail {
            get {
                return ResourceManager.GetString("successEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно завершена!.
        /// </summary>
        internal static string successEnde {
            get {
                return ResourceManager.GetString("successEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные клиента успешно сохранены.
        /// </summary>
        internal static string successSaveKD {
            get {
                return ResourceManager.GetString("successSaveKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше текстовое сообщение успешно отправлено.
        /// </summary>
        internal static string successSMS {
            get {
                return ResourceManager.GetString("successSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск интернетсоединения....
        /// </summary>
        internal static string sucheInternet {
            get {
                return ResourceManager.GetString("sucheInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не доступна поддержка ID .
        /// </summary>
        internal static string supportText {
            get {
                return ResourceManager.GetString("supportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . . ..
        /// </summary>
        internal static string user_blank {
            get {
                return ResourceManager.GetString("user_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить по электронной почте очень быстро и просто !.....
        /// </summary>
        internal static string user_email {
            get {
                return ResourceManager.GetString("user_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Круто! Вы можете зарегистрироваться и войти в систему под своим именем пользователя каждый раз. . . ..
        /// </summary>
        internal static string user_konto {
            get {
                return ResourceManager.GetString("user_konto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загрузить существующую учетную запись, чтобы использовать его позже или купить ваучер / купон, чтобы загрузить свой ​​счет! . . ..
        /// </summary>
        internal static string user_konto_aufladen {
            get {
                return ResourceManager.GetString("user_konto_aufladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение вызова на стационарные или мобильные устройства очень быстро и дешевле! . . ..
        /// </summary>
        internal static string user_phone {
            get {
                return ResourceManager.GetString("user_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень дешевые SMS-передачи! Очень просто, быстро и дешевле, чем мобильное устройство!.
        /// </summary>
        internal static string user_sms {
            get {
                return ResourceManager.GetString("user_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка временного пояса....
        /// </summary>
        internal static string zeitZone {
            get {
                return ResourceManager.GetString("zeitZone", resourceCulture);
            }
        }
    }
}
